plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/home/medicare-ai-agent/.openclaw/workspace/commission-tracker/build"
publishOrigin = "ui"
commandOrigin = "ui"
command = "npm run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]