// Auto-generated from exports/fight-packs-2026-08-15/google-import/CARRIER_ALL_FIGHTS_111.csv
const CARRIER_FIGHT_PACK_INDEX = {
  "ACOSTA|ARISTIDES|aetna": {
    "fightType": "Wrong_claw",
    "fightTypePlain": "Incorrect chargeback — reverse claw",
    "confidence": "HIGH",
    "sendOrder": 1,
    "carrier": "Aetna",
    "client": "ACOSTA,ARISTIDES",
    "agent": "Lina Hernandez",
    "effectiveDate": "2026-01-01",
    "amount": 240,
    "theiShare": 120,
    "bsiShare": 120,
    "errorCode": "OVER_CLAW",
    "proof": "New Business $347.00 (AETNA_BSI_STATEMENT_202601.xlsx); Chargeback $587.00 (AETNA_BSI_STATEMENT_202601.xlsx)",
    "askCarrier": "Reverse incorrect chargeback and repay BSI $240.00 for ACOSTA,ARISTIDES.",
    "note": "Send this packet first — solid claw proof",
    "state": "",
    "yearType": ""
  },
  "ACOSTA|LEMOS|MARIA|aetna": {
    "fightType": "Wrong_claw",
    "fightTypePlain": "Incorrect chargeback — reverse claw",
    "confidence": "HIGH",
    "sendOrder": 1,
    "carrier": "Aetna",
    "client": "LEMOS ACOSTA C,MARIA",
    "agent": "Lina Hernandez",
    "effectiveDate": "2026-01-01",
    "amount": 240,
    "theiShare": 120,
    "bsiShare": 120,
    "errorCode": "OVER_CLAW",
    "proof": "New Business $347.00 (AETNA_BSI_STATEMENT_202601.xlsx); Chargeback $587.00 (AETNA_BSI_STATEMENT_202601.xlsx)",
    "askCarrier": "Reverse incorrect chargeback and repay BSI $240.00 for LEMOS ACOSTA C,MARIA.",
    "note": "Send this packet first — solid claw proof",
    "state": "",
    "yearType": ""
  },
  "DE|MORALES|OLAY|ROSA|aetna": {
    "fightType": "Wrong_claw",
    "fightTypePlain": "Incorrect chargeback — reverse claw",
    "confidence": "HIGH",
    "sendOrder": 1,
    "carrier": "Aetna",
    "client": "MORALES DE OLAY,ROSA",
    "agent": "Lina Hernandez",
    "effectiveDate": "2026-01-01",
    "amount": 240,
    "theiShare": 120,
    "bsiShare": 120,
    "errorCode": "OVER_CLAW",
    "proof": "New Business $347.00 (AETNA_BSI_STATEMENT_202601.xlsx); Chargeback $587.00 (AETNA_BSI_STATEMENT_202601.xlsx)",
    "askCarrier": "Reverse incorrect chargeback and repay BSI $240.00 for MORALES DE OLAY,ROSA.",
    "note": "Send this packet first — solid claw proof",
    "state": "",
    "yearType": ""
  },
  "MARITZA|ROSARIO|VIRELLA|aetna": {
    "fightType": "Wrong_claw",
    "fightTypePlain": "Incorrect chargeback — reverse claw",
    "confidence": "HIGH",
    "sendOrder": 1,
    "carrier": "Aetna",
    "client": "ROSARIO VIRELLA,MARITZA",
    "agent": "Lina Hernandez",
    "effectiveDate": "2026-01-01",
    "amount": 240,
    "theiShare": 120,
    "bsiShare": 120,
    "errorCode": "OVER_CLAW",
    "proof": "New Business $347.00 (AETNA_BSI_STATEMENT_202601.xlsx); Chargeback $587.00 (AETNA_BSI_STATEMENT_202601.xlsx)",
    "askCarrier": "Reverse incorrect chargeback and repay BSI $240.00 for ROSARIO VIRELLA,MARITZA.",
    "note": "Send this packet first — solid claw proof",
    "state": "",
    "yearType": ""
  },
  "BLACKMON|JEWEL|aetna": {
    "fightType": "Wrong_claw",
    "fightTypePlain": "Incorrect chargeback — reverse claw",
    "confidence": "HIGH",
    "sendOrder": 1,
    "carrier": "Aetna",
    "client": "BLACKMON,JEWEL",
    "agent": "Christian Munoz",
    "effectiveDate": "2026-01-01",
    "amount": 200,
    "theiShare": 100,
    "bsiShare": 100,
    "errorCode": "OVER_CLAW",
    "proof": "Chargeback $40.00 (AETNA_BSI_STATEMENT_202603.csv); Chargeback $240.00 (AETNA_BSI_STATEMENT_202603.csv)",
    "askCarrier": "Reverse incorrect chargeback and repay BSI $200.00 for BLACKMON,JEWEL.",
    "note": "Send this packet first — solid claw proof",
    "state": "",
    "yearType": ""
  },
  "BARRIENTOS|HECTOR|aetna": {
    "fightType": "Wrong_claw",
    "fightTypePlain": "Incorrect chargeback — reverse claw",
    "confidence": "HIGH",
    "sendOrder": 1,
    "carrier": "Aetna",
    "client": "BARRIENTOS R,HECTOR",
    "agent": "Lina Hernandez",
    "effectiveDate": "2026-01-01",
    "amount": 125,
    "theiShare": 62.5,
    "bsiShare": 62.5,
    "errorCode": "OVER_CLAW",
    "proof": "New Business $347.00 (AETNA_BSI_STATEMENT_202601.xlsx); Chargeback $472.00 (AETNA_BSI_STATEMENT_202603.csv)",
    "askCarrier": "Reverse incorrect chargeback and repay BSI $125.00 for BARRIENTOS R,HECTOR.",
    "note": "Send this packet first — solid claw proof",
    "state": "",
    "yearType": ""
  },
  "HOLMES|WILLIE|aetna": {
    "fightType": "Wrong_claw",
    "fightTypePlain": "Incorrect chargeback — reverse claw",
    "confidence": "HIGH",
    "sendOrder": 1,
    "carrier": "Aetna",
    "client": "HOLMES L,WILLIE",
    "agent": "Lina Hernandez",
    "effectiveDate": "2026-01-01",
    "amount": 125,
    "theiShare": 62.5,
    "bsiShare": 62.5,
    "errorCode": "OVER_CLAW",
    "proof": "New Business $347.00 (AETNA_BSI_STATEMENT_202601.xlsx); Chargeback $472.00 (AETNA_BSI_STATEMENT_202602.csv)",
    "askCarrier": "Reverse incorrect chargeback and repay BSI $125.00 for HOLMES L,WILLIE.",
    "note": "Send this packet first — solid claw proof",
    "state": "",
    "yearType": ""
  },
  "BONNIE|MATTHEWS|aetna": {
    "fightType": "Wrong_claw",
    "fightTypePlain": "Incorrect chargeback — reverse claw",
    "confidence": "HIGH",
    "sendOrder": 1,
    "carrier": "Aetna",
    "client": "MATTHEWS G,BONNIE",
    "agent": "Lina Hernandez",
    "effectiveDate": "2026-01-01",
    "amount": 125,
    "theiShare": 62.5,
    "bsiShare": 62.5,
    "errorCode": "OVER_CLAW",
    "proof": "New Business $347.00 (AETNA_BSI_STATEMENT_202601.xlsx); Chargeback $472.00 (AETNA_BSI_STATEMENT_202603.csv)",
    "askCarrier": "Reverse incorrect chargeback and repay BSI $125.00 for MATTHEWS G,BONNIE.",
    "note": "Send this packet first — solid claw proof",
    "state": "",
    "yearType": ""
  },
  "JAIME|SANTIAGO|SANTIAGO|aetna": {
    "fightType": "Wrong_claw",
    "fightTypePlain": "Incorrect chargeback — reverse claw",
    "confidence": "HIGH",
    "sendOrder": 1,
    "carrier": "Aetna",
    "client": "SANTIAGO SANTIAGO E,JAIME",
    "agent": "Lina Hernandez",
    "effectiveDate": "2026-04-01",
    "amount": 125,
    "theiShare": 62.5,
    "bsiShare": 62.5,
    "errorCode": "OVER_CLAW",
    "proof": "New Business $391.00 (AETNA_BSI_STATEMENT_202601.xlsx); Chargeback $516.00 (AETNA_BSI_STATEMENT_202603.csv); New Business $425.25 (AETNA_BSI_STATEMENT_202603.csv)",
    "askCarrier": "Reverse incorrect chargeback and repay BSI $125.00 for SANTIAGO SANTIAGO E,JAIME.",
    "note": "Send this packet first — solid claw proof",
    "state": "",
    "yearType": ""
  },
  "MERCADO|ROSA|TORO|aetna": {
    "fightType": "Wrong_claw",
    "fightTypePlain": "Incorrect chargeback — reverse claw",
    "confidence": "HIGH",
    "sendOrder": 1,
    "carrier": "Aetna",
    "client": "TORO MERCADO,ROSA",
    "agent": "Lina Hernandez",
    "effectiveDate": "2026-01-01",
    "amount": 125,
    "theiShare": 62.5,
    "bsiShare": 62.5,
    "errorCode": "OVER_CLAW",
    "proof": "New Business $391.00 (AETNA_BSI_STATEMENT_202601.xlsx); Chargeback $516.00 (AETNA_BSI_STATEMENT_202603.csv); New Business $425.25 (AETNA_BSI_STATEMENT_202603.csv)",
    "askCarrier": "Reverse incorrect chargeback and repay BSI $125.00 for TORO MERCADO,ROSA.",
    "note": "Send this packet first — solid claw proof",
    "state": "",
    "yearType": ""
  },
  "CHERYL|WANKE|aetna": {
    "fightType": "Wrong_claw",
    "fightTypePlain": "Incorrect chargeback — reverse claw",
    "confidence": "HIGH",
    "sendOrder": 1,
    "carrier": "Aetna",
    "client": "WANKE L,CHERYL",
    "agent": "Cristy Witcher",
    "effectiveDate": "2026-01-01",
    "amount": 30,
    "theiShare": 15,
    "bsiShare": 15,
    "errorCode": "OVER_CLAW",
    "proof": "Chargeback $10.00 (AETNA_BSI_STATEMENT_202604.csv); Chargeback $40.00 (AETNA_BSI_STATEMENT_202604.csv)",
    "askCarrier": "Reverse incorrect chargeback and repay BSI $30.00 for WANKE L,CHERYL.",
    "note": "Send this packet first — solid claw proof",
    "state": "",
    "yearType": ""
  },
  "COLLIER|GENEVA|humana": {
    "fightType": "Wrong_claw",
    "fightTypePlain": "Incorrect chargeback — reverse claw",
    "confidence": "HIGH",
    "sendOrder": 1,
    "carrier": "Humana",
    "client": "GENEVA COLLIER M",
    "agent": "Jendy Vanheyningen",
    "effectiveDate": "2026-01-01",
    "amount": 90,
    "theiShare": 45,
    "bsiShare": 45,
    "errorCode": "DOUBLE_CLAW",
    "proof": "Chargeback $90.00 (HUMANA_BSI_STATEMENT_2026-03-01.xlsx); Agency Override $90.00 (Humana_BSI_Statement. 202607.CSV)",
    "askCarrier": "Reverse incorrect chargeback and repay BSI $90.00 for GENEVA COLLIER M.",
    "note": "Send this packet first — solid claw proof",
    "state": "",
    "yearType": ""
  },
  "ALVARADO|CARLOS|humana": {
    "fightType": "Wrong_claw",
    "fightTypePlain": "Incorrect chargeback — reverse claw",
    "confidence": "HIGH",
    "sendOrder": 1,
    "carrier": "Humana",
    "client": "CARLOS ALVARADO R",
    "agent": "Katy Robles",
    "effectiveDate": "2026-04-01",
    "amount": 3.75,
    "theiShare": 1.88,
    "bsiShare": 1.88,
    "errorCode": "OVER_CLAW",
    "proof": "New Business $120.00 (HUMANA_BSI_STATEMENT_2026-03-01.xlsx); Chargeback $123.75 (HUMANA_BSI_STATEMENT_2026-03-01.xlsx)",
    "askCarrier": "Reverse incorrect chargeback and repay BSI $3.75 for CARLOS ALVARADO R.",
    "note": "Send this packet first — solid claw proof",
    "state": "",
    "yearType": ""
  },
  "PATRICIA|SALINAS|humana": {
    "fightType": "Wrong_claw",
    "fightTypePlain": "Incorrect chargeback — reverse claw",
    "confidence": "HIGH",
    "sendOrder": 1,
    "carrier": "Humana",
    "client": "PATRICIA SALINAS",
    "agent": "Lina Hernandez",
    "effectiveDate": "2026-01-01",
    "amount": 3.25,
    "theiShare": 1.62,
    "bsiShare": 1.62,
    "errorCode": "OVER_CLAW",
    "proof": "New Business $347.00 (HUMANA_BSI_STATEMENT_2026-01-01.xlsx); Chargeback $90.00 (HUMANA_BSI_STATEMENT_2026-03-01.xlsx); Chargeback $260.25 (HUMANA_BSI_STATEMENT_2026-03-01.xlsx)",
    "askCarrier": "Reverse incorrect chargeback and repay BSI $3.25 for PATRICIA SALINAS.",
    "note": "Send this packet first — solid claw proof",
    "state": "",
    "yearType": ""
  },
  "MARTINEZ|RUBEN|humana": {
    "fightType": "Wrong_claw",
    "fightTypePlain": "Incorrect chargeback — reverse claw",
    "confidence": "HIGH",
    "sendOrder": 1,
    "carrier": "Humana",
    "client": "RUBEN MARTINEZ",
    "agent": "Lina Hernandez",
    "effectiveDate": "2026-01-01",
    "amount": 3.25,
    "theiShare": 1.62,
    "bsiShare": 1.62,
    "errorCode": "OVER_CLAW",
    "proof": "New Business $347.00 (HUMANA_BSI_STATEMENT_2026-01-01.xlsx); Chargeback $90.00 (HUMANA_BSI_STATEMENT_2026-04-01.xlsx); Chargeback $260.25 (HUMANA_BSI_STATEMENT_2026-04-01.xlsx)",
    "askCarrier": "Reverse incorrect chargeback and repay BSI $3.25 for RUBEN MARTINEZ.",
    "note": "Send this packet first — solid claw proof",
    "state": "",
    "yearType": ""
  },
  "FLORAEDNA|GO|unitedhealthcare": {
    "fightType": "Wrong_claw",
    "fightTypePlain": "Incorrect chargeback — reverse claw",
    "confidence": "HIGH",
    "sendOrder": 1,
    "carrier": "UnitedHealthcare",
    "client": "GO, FLORAEDNA S.",
    "agent": "Jendy Vanheyningen",
    "effectiveDate": "2026-04-01",
    "amount": 175,
    "theiShare": 87.5,
    "bsiShare": 87.5,
    "errorCode": "DOUBLE_CLAW",
    "proof": "New Business $175.00 (UHC_BSI_STATEMENT_2026-03-01.xlsx); Chargeback $175.00 (UHC_BSI_STATEMENT_2026-03-01.xlsx); Chargeback $175.00 (UHC_BSI_STATEMENT_2026-04-01.xlsx)",
    "askCarrier": "Reverse incorrect chargeback and repay BSI $175.00 for GO, FLORAEDNA S..",
    "note": "Send this packet first — solid claw proof",
    "state": "",
    "yearType": ""
  },
  "ILLOUZ|JOSEPH|unitedhealthcare": {
    "fightType": "Wrong_claw",
    "fightTypePlain": "Incorrect chargeback — reverse claw",
    "confidence": "HIGH",
    "sendOrder": 1,
    "carrier": "UnitedHealthcare",
    "client": "ILLOUZ, JOSEPH Y.",
    "agent": "Jendy Vanheyningen",
    "effectiveDate": "2026-04-01",
    "amount": 175,
    "theiShare": 87.5,
    "bsiShare": 87.5,
    "errorCode": "DOUBLE_CLAW",
    "proof": "New Business $175.00 (UHC_BSI_STATEMENT_2026-03-01.xlsx); Chargeback $175.00 (UHC_BSI_STATEMENT_2026-03-01.xlsx); Chargeback $175.00 (UHC_BSI_commission_statement_2929822_2026-07-01.xlsx)",
    "askCarrier": "Reverse incorrect chargeback and repay BSI $175.00 for ILLOUZ, JOSEPH Y..",
    "note": "Send this packet first — solid claw proof",
    "state": "",
    "yearType": ""
  },
  "ISIDRO|PEDRO|unitedhealthcare": {
    "fightType": "Wrong_claw",
    "fightTypePlain": "Incorrect chargeback — reverse claw",
    "confidence": "HIGH",
    "sendOrder": 1,
    "carrier": "UnitedHealthcare",
    "client": "PEDRO, ISIDRO R.",
    "agent": "Jendy Vanheyningen",
    "effectiveDate": "2026-04-01",
    "amount": 175,
    "theiShare": 87.5,
    "bsiShare": 87.5,
    "errorCode": "DOUBLE_CLAW",
    "proof": "New Business $175.00 (UHC_BSI_STATEMENT_2026-03-01.xlsx); Chargeback $175.00 (UHC_BSI_STATEMENT_2026-03-01.xlsx); Chargeback $175.00 (UHC_BSI_STATEMENT_2026-06-01.xlsx)",
    "askCarrier": "Reverse incorrect chargeback and repay BSI $175.00 for PEDRO, ISIDRO R..",
    "note": "Send this packet first — solid claw proof",
    "state": "",
    "yearType": ""
  },
  "FRANCINE|REYNOLDS|unitedhealthcare": {
    "fightType": "Wrong_claw",
    "fightTypePlain": "Incorrect chargeback — reverse claw",
    "confidence": "HIGH",
    "sendOrder": 1,
    "carrier": "UnitedHealthcare",
    "client": "REYNOLDS, FRANCINE R.",
    "agent": "Jendy Vanheyningen",
    "effectiveDate": "2026-04-01",
    "amount": 175,
    "theiShare": 87.5,
    "bsiShare": 87.5,
    "errorCode": "DOUBLE_CLAW",
    "proof": "New Business $175.00 (UHC_BSI_STATEMENT_2026-03-01.xlsx); Chargeback $175.00 (UHC_BSI_STATEMENT_2026-03-01.xlsx); Chargeback $175.00 (UHC_BSI_STATEMENT_2026-04-01.xlsx)",
    "askCarrier": "Reverse incorrect chargeback and repay BSI $175.00 for REYNOLDS, FRANCINE R..",
    "note": "Send this packet first — solid claw proof",
    "state": "",
    "yearType": ""
  },
  "LINDA|NEWMAN|VERNON|unitedhealthcare": {
    "fightType": "Wrong_claw",
    "fightTypePlain": "Incorrect chargeback — reverse claw",
    "confidence": "HIGH",
    "sendOrder": 1,
    "carrier": "UnitedHealthcare",
    "client": "VERNON NEWMAN, LINDA M.",
    "agent": "Jendy Vanheyningen",
    "effectiveDate": "2026-04-01",
    "amount": 160.41,
    "theiShare": 80.2,
    "bsiShare": 80.2,
    "errorCode": "DOUBLE_CLAW",
    "proof": "New Business $175.00 (UHC_BSI_STATEMENT_2026-03-01.xlsx); Chargeback $175.00 (UHC_BSI_STATEMENT_2026-03-01.xlsx); Chargeback $160.41 (UHC_BSI_STATEMENT_2026-04-01.xlsx)",
    "askCarrier": "Reverse incorrect chargeback and repay BSI $160.41 for VERNON NEWMAN, LINDA M..",
    "note": "Send this packet first — solid claw proof",
    "state": "",
    "yearType": ""
  },
  "ANA|BETANCOURT|DE|PATINO|devoted": {
    "fightType": "Missing_pay",
    "fightTypePlain": "Not on BSI — carrier never paid override",
    "confidence": "HIGH",
    "sendOrder": 2,
    "carrier": "Devoted",
    "client": "Ana Betancourt de Patino",
    "agent": "Noris Arcaya Martinez",
    "effectiveDate": "2026-04-01",
    "amount": 100,
    "theiShare": 50,
    "bsiShare": 50,
    "errorCode": "On Hector/active but NO pay on Carrier→BSI statements",
    "proof": "Hector=Approved; enrolled 2026-04-01; zero Agency Override on carrier→BSI uploads for this member",
    "askCarrier": "Member Ana Betancourt de Patino (eff 2026-04-01) is active on our books but does not appear on Brokerage Solutions (BSI) commission statements. Please pay the agency override of $100.00 per Devoted Initial · National · THEI 50%.",
    "note": "On Hector; missing from Carrier→BSI",
    "state": "FL",
    "yearType": "Initial"
  },
  "ANDERSON|CAROL|devoted": {
    "fightType": "Missing_pay",
    "fightTypePlain": "Not on BSI — carrier never paid override",
    "confidence": "HIGH",
    "sendOrder": 2,
    "carrier": "Devoted",
    "client": "Carol Anderson",
    "agent": "Cristy Witcher",
    "effectiveDate": "2026-08-01",
    "amount": 100,
    "theiShare": 50,
    "bsiShare": 50,
    "errorCode": "On Hector/active but NO pay on Carrier→BSI statements",
    "proof": "Hector=Enrolled; enrolled 2026-08-01; zero Agency Override on carrier→BSI uploads for this member",
    "askCarrier": "Member Carol Anderson (eff 2026-08-01) is active on our books but does not appear on Brokerage Solutions (BSI) commission statements. Please pay the agency override of $100.00 per Devoted Initial · National · THEI 50%.",
    "note": "On Hector; missing from Carrier→BSI",
    "state": "GA",
    "yearType": "Initial"
  },
  "ADAMS|IDA|humana": {
    "fightType": "Missing_pay",
    "fightTypePlain": "Not on BSI — carrier never paid override",
    "confidence": "HIGH",
    "sendOrder": 2,
    "carrier": "Humana",
    "client": "ADAMS, IDA",
    "agent": "ROBLES, KATY J",
    "effectiveDate": "2026-01-01",
    "amount": 150,
    "theiShare": 75,
    "bsiShare": 75,
    "errorCode": "On Hector/active but NO pay on Carrier→BSI statements",
    "proof": "Hector=Active Policy; enrolled 2026-01-01; zero Agency Override on carrier→BSI uploads for this member",
    "askCarrier": "Member ADAMS, IDA (eff 2026-01-01) is active on our books but does not appear on Brokerage Solutions (BSI) commission statements. Please pay the agency override of $150.00 per Humana Initial · National · THEI 50%.",
    "note": "On Hector; missing from Carrier→BSI",
    "state": "FL",
    "yearType": "Initial"
  },
  "AUTH|JOSEPH|humana": {
    "fightType": "Missing_pay",
    "fightTypePlain": "Not on BSI — carrier never paid override",
    "confidence": "HIGH",
    "sendOrder": 2,
    "carrier": "Humana",
    "client": "AUTH, JOSEPH",
    "agent": "ELCHAMI, ALAN",
    "effectiveDate": "2026-01-01",
    "amount": 150,
    "theiShare": 75,
    "bsiShare": 75,
    "errorCode": "On Hector/active but NO pay on Carrier→BSI statements",
    "proof": "Hector=Active Policy; enrolled 2026-01-01; zero Agency Override on carrier→BSI uploads for this member",
    "askCarrier": "Member AUTH, JOSEPH (eff 2026-01-01) is active on our books but does not appear on Brokerage Solutions (BSI) commission statements. Please pay the agency override of $150.00 per Humana Initial · National · THEI 50%.",
    "note": "On Hector; missing from Carrier→BSI",
    "state": "FL",
    "yearType": "Initial"
  },
  "BADGER|JR|OSCAR|humana": {
    "fightType": "Missing_pay",
    "fightTypePlain": "Not on BSI — carrier never paid override",
    "confidence": "HIGH",
    "sendOrder": 2,
    "carrier": "Humana",
    "client": "BADGER JR, OSCAR",
    "agent": "ROBLES, KATY J",
    "effectiveDate": "2026-01-01",
    "amount": 150,
    "theiShare": 75,
    "bsiShare": 75,
    "errorCode": "On Hector/active but NO pay on Carrier→BSI statements",
    "proof": "Hector=Active Policy; enrolled 2026-01-01; zero Agency Override on carrier→BSI uploads for this member",
    "askCarrier": "Member BADGER JR, OSCAR (eff 2026-01-01) is active on our books but does not appear on Brokerage Solutions (BSI) commission statements. Please pay the agency override of $150.00 per Humana Initial · National · THEI 50%.",
    "note": "On Hector; missing from Carrier→BSI",
    "state": "FL",
    "yearType": "Initial"
  },
  "ATTILIO|BAGNATO|humana": {
    "fightType": "Missing_pay",
    "fightTypePlain": "Not on BSI — carrier never paid override",
    "confidence": "HIGH",
    "sendOrder": 2,
    "carrier": "Humana",
    "client": "BAGNATO, ATTILIO",
    "agent": "ELCHAMI, ALAN",
    "effectiveDate": "2026-01-01",
    "amount": 150,
    "theiShare": 75,
    "bsiShare": 75,
    "errorCode": "On Hector/active but NO pay on Carrier→BSI statements",
    "proof": "Hector=Active Policy; enrolled 2026-01-01; zero Agency Override on carrier→BSI uploads for this member",
    "askCarrier": "Member BAGNATO, ATTILIO (eff 2026-01-01) is active on our books but does not appear on Brokerage Solutions (BSI) commission statements. Please pay the agency override of $150.00 per Humana Initial · National · THEI 50%.",
    "note": "On Hector; missing from Carrier→BSI",
    "state": "FL",
    "yearType": "Initial"
  },
  "BAPTISTE|FLORANA|humana": {
    "fightType": "Missing_pay",
    "fightTypePlain": "Not on BSI — carrier never paid override",
    "confidence": "HIGH",
    "sendOrder": 2,
    "carrier": "Humana",
    "client": "BAPTISTE, FLORANA",
    "agent": "ELCHAMI, ALAN",
    "effectiveDate": "2026-01-01",
    "amount": 150,
    "theiShare": 75,
    "bsiShare": 75,
    "errorCode": "On Hector/active but NO pay on Carrier→BSI statements",
    "proof": "Hector=Active Policy; enrolled 2026-01-01; zero Agency Override on carrier→BSI uploads for this member",
    "askCarrier": "Member BAPTISTE, FLORANA (eff 2026-01-01) is active on our books but does not appear on Brokerage Solutions (BSI) commission statements. Please pay the agency override of $150.00 per Humana Initial · National · THEI 50%.",
    "note": "On Hector; missing from Carrier→BSI",
    "state": "FL",
    "yearType": "Initial"
  },
  "BARRIOS|EDDIE|humana": {
    "fightType": "Missing_pay",
    "fightTypePlain": "Not on BSI — carrier never paid override",
    "confidence": "HIGH",
    "sendOrder": 2,
    "carrier": "Humana",
    "client": "BARRIOS, EDDIE",
    "agent": "ELCHAMI, ALAN",
    "effectiveDate": "2026-01-01",
    "amount": 150,
    "theiShare": 75,
    "bsiShare": 75,
    "errorCode": "On Hector/active but NO pay on Carrier→BSI statements",
    "proof": "Hector=Active Policy; enrolled 2026-01-01; zero Agency Override on carrier→BSI uploads for this member",
    "askCarrier": "Member BARRIOS, EDDIE (eff 2026-01-01) is active on our books but does not appear on Brokerage Solutions (BSI) commission statements. Please pay the agency override of $150.00 per Humana Initial · National · THEI 50%.",
    "note": "On Hector; missing from Carrier→BSI",
    "state": "FL",
    "yearType": "Initial"
  },
  "BARRIOS|VIRGINIA|humana": {
    "fightType": "Missing_pay",
    "fightTypePlain": "Not on BSI — carrier never paid override",
    "confidence": "HIGH",
    "sendOrder": 2,
    "carrier": "Humana",
    "client": "BARRIOS, VIRGINIA",
    "agent": "ELCHAMI, ALAN",
    "effectiveDate": "2026-01-01",
    "amount": 150,
    "theiShare": 75,
    "bsiShare": 75,
    "errorCode": "On Hector/active but NO pay on Carrier→BSI statements",
    "proof": "Hector=Active Policy; enrolled 2026-01-01; zero Agency Override on carrier→BSI uploads for this member",
    "askCarrier": "Member BARRIOS, VIRGINIA (eff 2026-01-01) is active on our books but does not appear on Brokerage Solutions (BSI) commission statements. Please pay the agency override of $150.00 per Humana Initial · National · THEI 50%.",
    "note": "On Hector; missing from Carrier→BSI",
    "state": "FL",
    "yearType": "Initial"
  },
  "BEAN|JOHN|JR|humana": {
    "fightType": "Missing_pay",
    "fightTypePlain": "Not on BSI — carrier never paid override",
    "confidence": "HIGH",
    "sendOrder": 2,
    "carrier": "Humana",
    "client": "BEAN JR., JOHN",
    "agent": "ROBLES, KATY J",
    "effectiveDate": "2026-01-01",
    "amount": 150,
    "theiShare": 75,
    "bsiShare": 75,
    "errorCode": "On Hector/active but NO pay on Carrier→BSI statements",
    "proof": "Hector=Active Policy; enrolled 2026-01-01; zero Agency Override on carrier→BSI uploads for this member",
    "askCarrier": "Member BEAN JR., JOHN (eff 2026-01-01) is active on our books but does not appear on Brokerage Solutions (BSI) commission statements. Please pay the agency override of $150.00 per Humana Initial · National · THEI 50%.",
    "note": "On Hector; missing from Carrier→BSI",
    "state": "FL",
    "yearType": "Initial"
  },
  "BREUIL|CAROL|humana": {
    "fightType": "Missing_pay",
    "fightTypePlain": "Not on BSI — carrier never paid override",
    "confidence": "HIGH",
    "sendOrder": 2,
    "carrier": "Humana",
    "client": "BREUIL, CAROL",
    "agent": "ELCHAMI, ALAN",
    "effectiveDate": "2026-01-01",
    "amount": 150,
    "theiShare": 75,
    "bsiShare": 75,
    "errorCode": "On Hector/active but NO pay on Carrier→BSI statements",
    "proof": "Hector=Active Policy; enrolled 2026-01-01; zero Agency Override on carrier→BSI uploads for this member",
    "askCarrier": "Member BREUIL, CAROL (eff 2026-01-01) is active on our books but does not appear on Brokerage Solutions (BSI) commission statements. Please pay the agency override of $150.00 per Humana Initial · National · THEI 50%.",
    "note": "On Hector; missing from Carrier→BSI",
    "state": "FL",
    "yearType": "Initial"
  },
  "BROUILLETTE|LISA|humana": {
    "fightType": "Missing_pay",
    "fightTypePlain": "Not on BSI — carrier never paid override",
    "confidence": "HIGH",
    "sendOrder": 2,
    "carrier": "Humana",
    "client": "BROUILLETTE, LISA",
    "agent": "CRUZ, ADRIAN B",
    "effectiveDate": "2026-01-01",
    "amount": 150,
    "theiShare": 75,
    "bsiShare": 75,
    "errorCode": "On Hector/active but NO pay on Carrier→BSI statements",
    "proof": "Hector=Active Policy; enrolled 2026-01-01; zero Agency Override on carrier→BSI uploads for this member",
    "askCarrier": "Member BROUILLETTE, LISA (eff 2026-01-01) is active on our books but does not appear on Brokerage Solutions (BSI) commission statements. Please pay the agency override of $150.00 per Humana Initial · National · THEI 50%.",
    "note": "On Hector; missing from Carrier→BSI",
    "state": "MA",
    "yearType": "Initial"
  },
  "CAPRON|DENNIS|humana": {
    "fightType": "Missing_pay",
    "fightTypePlain": "Not on BSI — carrier never paid override",
    "confidence": "HIGH",
    "sendOrder": 2,
    "carrier": "Humana",
    "client": "CAPRON, DENNIS",
    "agent": "ELCHAMI, ALAN",
    "effectiveDate": "2026-01-01",
    "amount": 150,
    "theiShare": 75,
    "bsiShare": 75,
    "errorCode": "On Hector/active but NO pay on Carrier→BSI statements",
    "proof": "Hector=Active Policy; enrolled 2026-01-01; zero Agency Override on carrier→BSI uploads for this member",
    "askCarrier": "Member CAPRON, DENNIS (eff 2026-01-01) is active on our books but does not appear on Brokerage Solutions (BSI) commission statements. Please pay the agency override of $150.00 per Humana Initial · National · THEI 50%.",
    "note": "On Hector; missing from Carrier→BSI",
    "state": "FL",
    "yearType": "Initial"
  },
  "CARTER|MARY|humana": {
    "fightType": "Missing_pay",
    "fightTypePlain": "Not on BSI — carrier never paid override",
    "confidence": "HIGH",
    "sendOrder": 2,
    "carrier": "Humana",
    "client": "CARTER, MARY",
    "agent": "VANHEYNINGEN, JENDY",
    "effectiveDate": "2026-03-01",
    "amount": 150,
    "theiShare": 75,
    "bsiShare": 75,
    "errorCode": "On Hector/active but NO pay on Carrier→BSI statements",
    "proof": "Hector=Paid; enrolled 2026-03-01; zero Agency Override on carrier→BSI uploads for this member",
    "askCarrier": "Member CARTER, MARY (eff 2026-03-01) is active on our books but does not appear on Brokerage Solutions (BSI) commission statements. Please pay the agency override of $150.00 per Humana Initial · National · THEI 50%.",
    "note": "On Hector; missing from Carrier→BSI",
    "state": "SC",
    "yearType": "Initial"
  },
  "CHANEY|JAQUELINE|humana": {
    "fightType": "Missing_pay",
    "fightTypePlain": "Not on BSI — carrier never paid override",
    "confidence": "HIGH",
    "sendOrder": 2,
    "carrier": "Humana",
    "client": "CHANEY, JAQUELINE",
    "agent": "MENDIETA, HORACIO G",
    "effectiveDate": "2026-01-01",
    "amount": 150,
    "theiShare": 75,
    "bsiShare": 75,
    "errorCode": "On Hector/active but NO pay on Carrier→BSI statements",
    "proof": "Hector=Active Policy; enrolled 2026-01-01; zero Agency Override on carrier→BSI uploads for this member",
    "askCarrier": "Member CHANEY, JAQUELINE (eff 2026-01-01) is active on our books but does not appear on Brokerage Solutions (BSI) commission statements. Please pay the agency override of $150.00 per Humana Initial · National · THEI 50%.",
    "note": "On Hector; missing from Carrier→BSI",
    "state": "FL",
    "yearType": "Initial"
  },
  "DARDER|MARIA|TERESA|humana": {
    "fightType": "Missing_pay",
    "fightTypePlain": "Not on BSI — carrier never paid override",
    "confidence": "HIGH",
    "sendOrder": 2,
    "carrier": "Humana",
    "client": "DARDER, MARIA TERESA",
    "agent": "DEL VALLE, ERIC",
    "effectiveDate": "2026-01-01",
    "amount": 150,
    "theiShare": 75,
    "bsiShare": 75,
    "errorCode": "On Hector/active but NO pay on Carrier→BSI statements",
    "proof": "Hector=Active Policy; enrolled 2026-01-01; zero Agency Override on carrier→BSI uploads for this member",
    "askCarrier": "Member DARDER, MARIA TERESA (eff 2026-01-01) is active on our books but does not appear on Brokerage Solutions (BSI) commission statements. Please pay the agency override of $150.00 per Humana Initial · National · THEI 50%.",
    "note": "On Hector; missing from Carrier→BSI",
    "state": "FL",
    "yearType": "Initial"
  },
  "DECHTER|JOEL|humana": {
    "fightType": "Missing_pay",
    "fightTypePlain": "Not on BSI — carrier never paid override",
    "confidence": "HIGH",
    "sendOrder": 2,
    "carrier": "Humana",
    "client": "DECHTER, JOEL",
    "agent": "TAYLOR, JILL A",
    "effectiveDate": "2026-01-01",
    "amount": 150,
    "theiShare": 75,
    "bsiShare": 75,
    "errorCode": "On Hector/active but NO pay on Carrier→BSI statements",
    "proof": "Hector=Active Policy; enrolled 2026-01-01; zero Agency Override on carrier→BSI uploads for this member",
    "askCarrier": "Member DECHTER, JOEL (eff 2026-01-01) is active on our books but does not appear on Brokerage Solutions (BSI) commission statements. Please pay the agency override of $150.00 per Humana Initial · National · THEI 50%.",
    "note": "On Hector; missing from Carrier→BSI",
    "state": "FL",
    "yearType": "Initial"
  },
  "DEPEW|LESLIE|humana": {
    "fightType": "Missing_pay",
    "fightTypePlain": "Not on BSI — carrier never paid override",
    "confidence": "HIGH",
    "sendOrder": 2,
    "carrier": "Humana",
    "client": "DEPEW, LESLIE",
    "agent": "NICHELSON, JEREMY J",
    "effectiveDate": "2026-01-01",
    "amount": 150,
    "theiShare": 75,
    "bsiShare": 75,
    "errorCode": "On Hector/active but NO pay on Carrier→BSI statements",
    "proof": "Hector=Active Policy; enrolled 2026-01-01; zero Agency Override on carrier→BSI uploads for this member",
    "askCarrier": "Member DEPEW, LESLIE (eff 2026-01-01) is active on our books but does not appear on Brokerage Solutions (BSI) commission statements. Please pay the agency override of $150.00 per Humana Initial · National · THEI 50%.",
    "note": "On Hector; missing from Carrier→BSI",
    "state": "AZ",
    "yearType": "Initial"
  },
  "ANA|DESCHAPELLES|humana": {
    "fightType": "Missing_pay",
    "fightTypePlain": "Not on BSI — carrier never paid override",
    "confidence": "HIGH",
    "sendOrder": 2,
    "carrier": "Humana",
    "client": "DESCHAPELLES, ANA",
    "agent": "ELCHAMI, ALAN",
    "effectiveDate": "2026-02-01",
    "amount": 150,
    "theiShare": 75,
    "bsiShare": 75,
    "errorCode": "On Hector/active but NO pay on Carrier→BSI statements",
    "proof": "Hector=Paid; enrolled 2026-02-01; zero Agency Override on carrier→BSI uploads for this member",
    "askCarrier": "Member DESCHAPELLES, ANA (eff 2026-02-01) is active on our books but does not appear on Brokerage Solutions (BSI) commission statements. Please pay the agency override of $150.00 per Humana Initial · National · THEI 50%.",
    "note": "On Hector; missing from Carrier→BSI",
    "state": "FL",
    "yearType": "Initial"
  },
  "EL|MASRI|SUSAN|humana": {
    "fightType": "Missing_pay",
    "fightTypePlain": "Not on BSI — carrier never paid override",
    "confidence": "HIGH",
    "sendOrder": 2,
    "carrier": "Humana",
    "client": "EL-MASRI, SUSAN",
    "agent": "SANTIAGO, IVAN",
    "effectiveDate": "2026-01-01",
    "amount": 150,
    "theiShare": 75,
    "bsiShare": 75,
    "errorCode": "On Hector/active but NO pay on Carrier→BSI statements",
    "proof": "Hector=Active Policy; enrolled 2026-01-01; zero Agency Override on carrier→BSI uploads for this member",
    "askCarrier": "Member EL-MASRI, SUSAN (eff 2026-01-01) is active on our books but does not appear on Brokerage Solutions (BSI) commission statements. Please pay the agency override of $150.00 per Humana Initial · National · THEI 50%.",
    "note": "On Hector; missing from Carrier→BSI",
    "state": "FL",
    "yearType": "Initial"
  },
  "ESCOBAR|GONZALEZ|MARIA|humana": {
    "fightType": "Missing_pay",
    "fightTypePlain": "Not on BSI — carrier never paid override",
    "confidence": "HIGH",
    "sendOrder": 2,
    "carrier": "Humana",
    "client": "ESCOBAR GONZALEZ, MARIA",
    "agent": "ROSTRAN, PAULETTE",
    "effectiveDate": "2026-08-01",
    "amount": 150,
    "theiShare": 75,
    "bsiShare": 75,
    "errorCode": "On Hector/active but NO pay on Carrier→BSI statements",
    "proof": "Hector=Active Policy; enrolled 2026-08-01; zero Agency Override on carrier→BSI uploads for this member",
    "askCarrier": "Member ESCOBAR GONZALEZ, MARIA (eff 2026-08-01) is active on our books but does not appear on Brokerage Solutions (BSI) commission statements. Please pay the agency override of $150.00 per Humana Initial · National · THEI 50%.",
    "note": "On Hector; missing from Carrier→BSI",
    "state": "FL",
    "yearType": "Initial"
  },
  "EVANS|VALDORA|humana": {
    "fightType": "Missing_pay",
    "fightTypePlain": "Not on BSI — carrier never paid override",
    "confidence": "HIGH",
    "sendOrder": 2,
    "carrier": "Humana",
    "client": "EVANS, VALDORA",
    "agent": "VANHEYNINGEN, JENDY",
    "effectiveDate": "2026-08-01",
    "amount": 150,
    "theiShare": 75,
    "bsiShare": 75,
    "errorCode": "On Hector/active but NO pay on Carrier→BSI statements",
    "proof": "Hector=Active Policy; enrolled 2026-08-01; zero Agency Override on carrier→BSI uploads for this member",
    "askCarrier": "Member EVANS, VALDORA (eff 2026-08-01) is active on our books but does not appear on Brokerage Solutions (BSI) commission statements. Please pay the agency override of $150.00 per Humana Initial · National · THEI 50%.",
    "note": "On Hector; missing from Carrier→BSI",
    "state": "SC",
    "yearType": "Initial"
  },
  "ANITA|FLORES|humana": {
    "fightType": "Missing_pay",
    "fightTypePlain": "Not on BSI — carrier never paid override",
    "confidence": "HIGH",
    "sendOrder": 2,
    "carrier": "Humana",
    "client": "FLORES, ANITA",
    "agent": "VANHEYNINGEN, JENDY",
    "effectiveDate": "2026-02-01",
    "amount": 150,
    "theiShare": 75,
    "bsiShare": 75,
    "errorCode": "On Hector/active but NO pay on Carrier→BSI statements",
    "proof": "Hector=Paid; enrolled 2026-02-01; zero Agency Override on carrier→BSI uploads for this member",
    "askCarrier": "Member FLORES, ANITA (eff 2026-02-01) is active on our books but does not appear on Brokerage Solutions (BSI) commission statements. Please pay the agency override of $150.00 per Humana Initial · National · THEI 50%.",
    "note": "On Hector; missing from Carrier→BSI",
    "state": "OR",
    "yearType": "Initial"
  },
  "FORD|LINDA|PLUMMER|humana": {
    "fightType": "Missing_pay",
    "fightTypePlain": "Not on BSI — carrier never paid override",
    "confidence": "HIGH",
    "sendOrder": 2,
    "carrier": "Humana",
    "client": "FORD PLUMMER, LINDA",
    "agent": "PEREZ, YAHOSKA G",
    "effectiveDate": "2026-01-01",
    "amount": 150,
    "theiShare": 75,
    "bsiShare": 75,
    "errorCode": "On Hector/active but NO pay on Carrier→BSI statements",
    "proof": "Hector=Active Policy; enrolled 2026-01-01; zero Agency Override on carrier→BSI uploads for this member",
    "askCarrier": "Member FORD PLUMMER, LINDA (eff 2026-01-01) is active on our books but does not appear on Brokerage Solutions (BSI) commission statements. Please pay the agency override of $150.00 per Humana Initial · National · THEI 50%.",
    "note": "On Hector; missing from Carrier→BSI",
    "state": "FL",
    "yearType": "Initial"
  },
  "FOUST|HARLEY|humana": {
    "fightType": "Missing_pay",
    "fightTypePlain": "Not on BSI — carrier never paid override",
    "confidence": "HIGH",
    "sendOrder": 2,
    "carrier": "Humana",
    "client": "FOUST, HARLEY",
    "agent": "MEJIA, DIANA L",
    "effectiveDate": "2026-01-01",
    "amount": 150,
    "theiShare": 75,
    "bsiShare": 75,
    "errorCode": "On Hector/active but NO pay on Carrier→BSI statements",
    "proof": "Hector=Active Policy; enrolled 2026-01-01; zero Agency Override on carrier→BSI uploads for this member",
    "askCarrier": "Member FOUST, HARLEY (eff 2026-01-01) is active on our books but does not appear on Brokerage Solutions (BSI) commission statements. Please pay the agency override of $150.00 per Humana Initial · National · THEI 50%.",
    "note": "On Hector; missing from Carrier→BSI",
    "state": "FL",
    "yearType": "Initial"
  },
  "FOUST|NANCY|humana": {
    "fightType": "Missing_pay",
    "fightTypePlain": "Not on BSI — carrier never paid override",
    "confidence": "HIGH",
    "sendOrder": 2,
    "carrier": "Humana",
    "client": "FOUST, NANCY",
    "agent": "MEJIA, DIANA L",
    "effectiveDate": "2026-01-01",
    "amount": 150,
    "theiShare": 75,
    "bsiShare": 75,
    "errorCode": "On Hector/active but NO pay on Carrier→BSI statements",
    "proof": "Hector=Active Policy; enrolled 2026-01-01; zero Agency Override on carrier→BSI uploads for this member",
    "askCarrier": "Member FOUST, NANCY (eff 2026-01-01) is active on our books but does not appear on Brokerage Solutions (BSI) commission statements. Please pay the agency override of $150.00 per Humana Initial · National · THEI 50%.",
    "note": "On Hector; missing from Carrier→BSI",
    "state": "FL",
    "yearType": "Initial"
  },
  "FRASICA|ROSA|humana": {
    "fightType": "Missing_pay",
    "fightTypePlain": "Not on BSI — carrier never paid override",
    "confidence": "HIGH",
    "sendOrder": 2,
    "carrier": "Humana",
    "client": "FRASICA, ROSA",
    "agent": "RIVEROS, ALIRIA",
    "effectiveDate": "2026-02-01",
    "amount": 150,
    "theiShare": 75,
    "bsiShare": 75,
    "errorCode": "On Hector/active but NO pay on Carrier→BSI statements",
    "proof": "Hector=Active Policy; enrolled 2026-02-01; zero Agency Override on carrier→BSI uploads for this member",
    "askCarrier": "Member FRASICA, ROSA (eff 2026-02-01) is active on our books but does not appear on Brokerage Solutions (BSI) commission statements. Please pay the agency override of $150.00 per Humana Initial · National · THEI 50%.",
    "note": "On Hector; missing from Carrier→BSI",
    "state": "FL",
    "yearType": "Initial"
  },
  "FAUSTO|GOMEZ|humana": {
    "fightType": "Missing_pay",
    "fightTypePlain": "Not on BSI — carrier never paid override",
    "confidence": "HIGH",
    "sendOrder": 2,
    "carrier": "Humana",
    "client": "GOMEZ, FAUSTO",
    "agent": "NICHELSON, JEREMY J",
    "effectiveDate": "2026-01-01",
    "amount": 150,
    "theiShare": 75,
    "bsiShare": 75,
    "errorCode": "On Hector/active but NO pay on Carrier→BSI statements",
    "proof": "Hector=Active Policy; enrolled 2026-01-01; zero Agency Override on carrier→BSI uploads for this member",
    "askCarrier": "Member GOMEZ, FAUSTO (eff 2026-01-01) is active on our books but does not appear on Brokerage Solutions (BSI) commission statements. Please pay the agency override of $150.00 per Humana Initial · National · THEI 50%.",
    "note": "On Hector; missing from Carrier→BSI",
    "state": "FL",
    "yearType": "Initial"
  },
  "GONZALEZ|JOSE|humana": {
    "fightType": "Missing_pay",
    "fightTypePlain": "Not on BSI — carrier never paid override",
    "confidence": "HIGH",
    "sendOrder": 2,
    "carrier": "Humana",
    "client": "GONZALEZ, JOSE",
    "agent": "ROSTRAN, PAULETTE",
    "effectiveDate": "2026-08-01",
    "amount": 150,
    "theiShare": 75,
    "bsiShare": 75,
    "errorCode": "On Hector/active but NO pay on Carrier→BSI statements",
    "proof": "Hector=Active Policy; enrolled 2026-08-01; zero Agency Override on carrier→BSI uploads for this member",
    "askCarrier": "Member GONZALEZ, JOSE (eff 2026-08-01) is active on our books but does not appear on Brokerage Solutions (BSI) commission statements. Please pay the agency override of $150.00 per Humana Initial · National · THEI 50%.",
    "note": "On Hector; missing from Carrier→BSI",
    "state": "FL",
    "yearType": "Initial"
  },
  "GRIEGO|JOSE|humana": {
    "fightType": "Missing_pay",
    "fightTypePlain": "Not on BSI — carrier never paid override",
    "confidence": "HIGH",
    "sendOrder": 2,
    "carrier": "Humana",
    "client": "GRIEGO, JOSE",
    "agent": "NICHELSON, JEREMY J",
    "effectiveDate": "2026-01-01",
    "amount": 150,
    "theiShare": 75,
    "bsiShare": 75,
    "errorCode": "On Hector/active but NO pay on Carrier→BSI statements",
    "proof": "Hector=Active Policy; enrolled 2026-01-01; zero Agency Override on carrier→BSI uploads for this member",
    "askCarrier": "Member GRIEGO, JOSE (eff 2026-01-01) is active on our books but does not appear on Brokerage Solutions (BSI) commission statements. Please pay the agency override of $150.00 per Humana Initial · National · THEI 50%.",
    "note": "On Hector; missing from Carrier→BSI",
    "state": "FL",
    "yearType": "Initial"
  },
  "GRIEGO|MARIA|humana": {
    "fightType": "Missing_pay",
    "fightTypePlain": "Not on BSI — carrier never paid override",
    "confidence": "HIGH",
    "sendOrder": 2,
    "carrier": "Humana",
    "client": "GRIEGO, MARIA",
    "agent": "NICHELSON, JEREMY J",
    "effectiveDate": "2026-01-01",
    "amount": 150,
    "theiShare": 75,
    "bsiShare": 75,
    "errorCode": "On Hector/active but NO pay on Carrier→BSI statements",
    "proof": "Hector=Active Policy; enrolled 2026-01-01; zero Agency Override on carrier→BSI uploads for this member",
    "askCarrier": "Member GRIEGO, MARIA (eff 2026-01-01) is active on our books but does not appear on Brokerage Solutions (BSI) commission statements. Please pay the agency override of $150.00 per Humana Initial · National · THEI 50%.",
    "note": "On Hector; missing from Carrier→BSI",
    "state": "FL",
    "yearType": "Initial"
  },
  "HAMMERLE|KATHRYN|TITSWORTH|humana": {
    "fightType": "Missing_pay",
    "fightTypePlain": "Not on BSI — carrier never paid override",
    "confidence": "HIGH",
    "sendOrder": 2,
    "carrier": "Humana",
    "client": "HAMMERLE-TITSWORTH, KATHRYN",
    "agent": "MENDIETA, HORACIO G",
    "effectiveDate": "2026-01-01",
    "amount": 150,
    "theiShare": 75,
    "bsiShare": 75,
    "errorCode": "On Hector/active but NO pay on Carrier→BSI statements",
    "proof": "Hector=Active Policy; enrolled 2026-01-01; zero Agency Override on carrier→BSI uploads for this member",
    "askCarrier": "Member HAMMERLE-TITSWORTH, KATHRYN (eff 2026-01-01) is active on our books but does not appear on Brokerage Solutions (BSI) commission statements. Please pay the agency override of $150.00 per Humana Initial · National · THEI 50%.",
    "note": "On Hector; missing from Carrier→BSI",
    "state": "FL",
    "yearType": "Initial"
  },
  "HARRIS|HATTIE|humana": {
    "fightType": "Missing_pay",
    "fightTypePlain": "Not on BSI — carrier never paid override",
    "confidence": "HIGH",
    "sendOrder": 2,
    "carrier": "Humana",
    "client": "HARRIS, HATTIE",
    "agent": "ELCHAMI, ALAN",
    "effectiveDate": "2026-01-01",
    "amount": 150,
    "theiShare": 75,
    "bsiShare": 75,
    "errorCode": "On Hector/active but NO pay on Carrier→BSI statements",
    "proof": "Hector=Active Policy; enrolled 2026-01-01; zero Agency Override on carrier→BSI uploads for this member",
    "askCarrier": "Member HARRIS, HATTIE (eff 2026-01-01) is active on our books but does not appear on Brokerage Solutions (BSI) commission statements. Please pay the agency override of $150.00 per Humana Initial · National · THEI 50%.",
    "note": "On Hector; missing from Carrier→BSI",
    "state": "FL",
    "yearType": "Initial"
  },
  "ISAACSON|LAURENCE|humana": {
    "fightType": "Missing_pay",
    "fightTypePlain": "Not on BSI — carrier never paid override",
    "confidence": "HIGH",
    "sendOrder": 2,
    "carrier": "Humana",
    "client": "ISAACSON, LAURENCE",
    "agent": "ELCHAMI, ALAN",
    "effectiveDate": "2026-01-01",
    "amount": 150,
    "theiShare": 75,
    "bsiShare": 75,
    "errorCode": "On Hector/active but NO pay on Carrier→BSI statements",
    "proof": "Hector=Active Policy; enrolled 2026-01-01; zero Agency Override on carrier→BSI uploads for this member",
    "askCarrier": "Member ISAACSON, LAURENCE (eff 2026-01-01) is active on our books but does not appear on Brokerage Solutions (BSI) commission statements. Please pay the agency override of $150.00 per Humana Initial · National · THEI 50%.",
    "note": "On Hector; missing from Carrier→BSI",
    "state": "FL",
    "yearType": "Initial"
  },
  "ISAACSON|LORI|humana": {
    "fightType": "Missing_pay",
    "fightTypePlain": "Not on BSI — carrier never paid override",
    "confidence": "HIGH",
    "sendOrder": 2,
    "carrier": "Humana",
    "client": "ISAACSON, LORI",
    "agent": "ELCHAMI, ALAN",
    "effectiveDate": "2026-01-01",
    "amount": 150,
    "theiShare": 75,
    "bsiShare": 75,
    "errorCode": "On Hector/active but NO pay on Carrier→BSI statements",
    "proof": "Hector=Active Policy; enrolled 2026-01-01; zero Agency Override on carrier→BSI uploads for this member",
    "askCarrier": "Member ISAACSON, LORI (eff 2026-01-01) is active on our books but does not appear on Brokerage Solutions (BSI) commission statements. Please pay the agency override of $150.00 per Humana Initial · National · THEI 50%.",
    "note": "On Hector; missing from Carrier→BSI",
    "state": "FL",
    "yearType": "Initial"
  },
  "JACKSON|NESCETA|humana": {
    "fightType": "Missing_pay",
    "fightTypePlain": "Not on BSI — carrier never paid override",
    "confidence": "HIGH",
    "sendOrder": 2,
    "carrier": "Humana",
    "client": "JACKSON, NESCETA",
    "agent": "ELCHAMI, ALAN",
    "effectiveDate": "2026-01-01",
    "amount": 150,
    "theiShare": 75,
    "bsiShare": 75,
    "errorCode": "On Hector/active but NO pay on Carrier→BSI statements",
    "proof": "Hector=Active Policy; enrolled 2026-01-01; zero Agency Override on carrier→BSI uploads for this member",
    "askCarrier": "Member JACKSON, NESCETA (eff 2026-01-01) is active on our books but does not appear on Brokerage Solutions (BSI) commission statements. Please pay the agency override of $150.00 per Humana Initial · National · THEI 50%.",
    "note": "On Hector; missing from Carrier→BSI",
    "state": "FL",
    "yearType": "Initial"
  },
  "JEWETT|RANDY|humana": {
    "fightType": "Missing_pay",
    "fightTypePlain": "Not on BSI — carrier never paid override",
    "confidence": "HIGH",
    "sendOrder": 2,
    "carrier": "Humana",
    "client": "JEWETT, RANDY",
    "agent": "ROSTRAN, PAULETTE",
    "effectiveDate": "2026-01-01",
    "amount": 150,
    "theiShare": 75,
    "bsiShare": 75,
    "errorCode": "On Hector/active but NO pay on Carrier→BSI statements",
    "proof": "Hector=Active Policy; enrolled 2026-01-01; zero Agency Override on carrier→BSI uploads for this member",
    "askCarrier": "Member JEWETT, RANDY (eff 2026-01-01) is active on our books but does not appear on Brokerage Solutions (BSI) commission statements. Please pay the agency override of $150.00 per Humana Initial · National · THEI 50%.",
    "note": "On Hector; missing from Carrier→BSI",
    "state": "FL",
    "yearType": "Initial"
  },
  "CLARSEYLUALEE|JUDY|humana": {
    "fightType": "Missing_pay",
    "fightTypePlain": "Not on BSI — carrier never paid override",
    "confidence": "HIGH",
    "sendOrder": 2,
    "carrier": "Humana",
    "client": "JUDY, CLARSEYLUALEE",
    "agent": "VANHEYNINGEN, JENDY",
    "effectiveDate": "2026-03-01",
    "amount": 150,
    "theiShare": 75,
    "bsiShare": 75,
    "errorCode": "On Hector/active but NO pay on Carrier→BSI statements",
    "proof": "Hector=Paid; enrolled 2026-03-01; zero Agency Override on carrier→BSI uploads for this member",
    "askCarrier": "Member JUDY, CLARSEYLUALEE (eff 2026-03-01) is active on our books but does not appear on Brokerage Solutions (BSI) commission statements. Please pay the agency override of $150.00 per Humana Initial · National · THEI 50%.",
    "note": "On Hector; missing from Carrier→BSI",
    "state": "VA",
    "yearType": "Initial"
  },
  "DENISE|JULIEN|humana": {
    "fightType": "Missing_pay",
    "fightTypePlain": "Not on BSI — carrier never paid override",
    "confidence": "HIGH",
    "sendOrder": 2,
    "carrier": "Humana",
    "client": "JULIEN, DENISE",
    "agent": "ELCHAMI, ALAN",
    "effectiveDate": "2026-01-01",
    "amount": 150,
    "theiShare": 75,
    "bsiShare": 75,
    "errorCode": "On Hector/active but NO pay on Carrier→BSI statements",
    "proof": "Hector=Active Policy; enrolled 2026-01-01; zero Agency Override on carrier→BSI uploads for this member",
    "askCarrier": "Member JULIEN, DENISE (eff 2026-01-01) is active on our books but does not appear on Brokerage Solutions (BSI) commission statements. Please pay the agency override of $150.00 per Humana Initial · National · THEI 50%.",
    "note": "On Hector; missing from Carrier→BSI",
    "state": "FL",
    "yearType": "Initial"
  },
  "DANIEL|LESLIE|humana": {
    "fightType": "Missing_pay",
    "fightTypePlain": "Not on BSI — carrier never paid override",
    "confidence": "HIGH",
    "sendOrder": 2,
    "carrier": "Humana",
    "client": "LESLIE, DANIEL",
    "agent": "ELCHAMI, ALAN",
    "effectiveDate": "2026-01-01",
    "amount": 150,
    "theiShare": 75,
    "bsiShare": 75,
    "errorCode": "On Hector/active but NO pay on Carrier→BSI statements",
    "proof": "Hector=Active Policy; enrolled 2026-01-01; zero Agency Override on carrier→BSI uploads for this member",
    "askCarrier": "Member LESLIE, DANIEL (eff 2026-01-01) is active on our books but does not appear on Brokerage Solutions (BSI) commission statements. Please pay the agency override of $150.00 per Humana Initial · National · THEI 50%.",
    "note": "On Hector; missing from Carrier→BSI",
    "state": "FL",
    "yearType": "Initial"
  },
  "LESLIE|MARLENE|humana": {
    "fightType": "Missing_pay",
    "fightTypePlain": "Not on BSI — carrier never paid override",
    "confidence": "HIGH",
    "sendOrder": 2,
    "carrier": "Humana",
    "client": "LESLIE, MARLENE",
    "agent": "ELCHAMI, ALAN",
    "effectiveDate": "2026-01-01",
    "amount": 150,
    "theiShare": 75,
    "bsiShare": 75,
    "errorCode": "On Hector/active but NO pay on Carrier→BSI statements",
    "proof": "Hector=Active Policy; enrolled 2026-01-01; zero Agency Override on carrier→BSI uploads for this member",
    "askCarrier": "Member LESLIE, MARLENE (eff 2026-01-01) is active on our books but does not appear on Brokerage Solutions (BSI) commission statements. Please pay the agency override of $150.00 per Humana Initial · National · THEI 50%.",
    "note": "On Hector; missing from Carrier→BSI",
    "state": "FL",
    "yearType": "Initial"
  },
  "MARTINEZ|PARRA|RAFAEL|humana": {
    "fightType": "Missing_pay",
    "fightTypePlain": "Not on BSI — carrier never paid override",
    "confidence": "HIGH",
    "sendOrder": 2,
    "carrier": "Humana",
    "client": "MARTINEZ PARRA, RAFAEL",
    "agent": "ELCHAMI, ALAN",
    "effectiveDate": "2026-01-01",
    "amount": 150,
    "theiShare": 75,
    "bsiShare": 75,
    "errorCode": "On Hector/active but NO pay on Carrier→BSI statements",
    "proof": "Hector=Active Policy; enrolled 2026-01-01; zero Agency Override on carrier→BSI uploads for this member",
    "askCarrier": "Member MARTINEZ PARRA, RAFAEL (eff 2026-01-01) is active on our books but does not appear on Brokerage Solutions (BSI) commission statements. Please pay the agency override of $150.00 per Humana Initial · National · THEI 50%.",
    "note": "On Hector; missing from Carrier→BSI",
    "state": "FL",
    "yearType": "Initial"
  },
  "MARTINEZ|VERONICA|humana": {
    "fightType": "Missing_pay",
    "fightTypePlain": "Not on BSI — carrier never paid override",
    "confidence": "HIGH",
    "sendOrder": 2,
    "carrier": "Humana",
    "client": "MARTINEZ, VERONICA",
    "agent": "MUNOZ, CHRISTIAN",
    "effectiveDate": "2026-01-01",
    "amount": 150,
    "theiShare": 75,
    "bsiShare": 75,
    "errorCode": "On Hector/active but NO pay on Carrier→BSI statements",
    "proof": "Hector=Active Policy; enrolled 2026-01-01; zero Agency Override on carrier→BSI uploads for this member",
    "askCarrier": "Member MARTINEZ, VERONICA (eff 2026-01-01) is active on our books but does not appear on Brokerage Solutions (BSI) commission statements. Please pay the agency override of $150.00 per Humana Initial · National · THEI 50%.",
    "note": "On Hector; missing from Carrier→BSI",
    "state": "FL",
    "yearType": "Initial"
  },
  "MASSA|MICHAEL|humana": {
    "fightType": "Missing_pay",
    "fightTypePlain": "Not on BSI — carrier never paid override",
    "confidence": "HIGH",
    "sendOrder": 2,
    "carrier": "Humana",
    "client": "MASSA, MICHAEL",
    "agent": "MUNOZ, CHRISTIAN",
    "effectiveDate": "2026-01-01",
    "amount": 150,
    "theiShare": 75,
    "bsiShare": 75,
    "errorCode": "On Hector/active but NO pay on Carrier→BSI statements",
    "proof": "Hector=Active Policy; enrolled 2026-01-01; zero Agency Override on carrier→BSI uploads for this member",
    "askCarrier": "Member MASSA, MICHAEL (eff 2026-01-01) is active on our books but does not appear on Brokerage Solutions (BSI) commission statements. Please pay the agency override of $150.00 per Humana Initial · National · THEI 50%.",
    "note": "On Hector; missing from Carrier→BSI",
    "state": "FL",
    "yearType": "Initial"
  },
  "GENNETTE|MCDANIEL|humana": {
    "fightType": "Missing_pay",
    "fightTypePlain": "Not on BSI — carrier never paid override",
    "confidence": "HIGH",
    "sendOrder": 2,
    "carrier": "Humana",
    "client": "MCDANIEL, GENNETTE",
    "agent": "PAYTON, TYLER DUANE D",
    "effectiveDate": "2026-01-01",
    "amount": 150,
    "theiShare": 75,
    "bsiShare": 75,
    "errorCode": "On Hector/active but NO pay on Carrier→BSI statements",
    "proof": "Hector=Active Policy; enrolled 2026-01-01; zero Agency Override on carrier→BSI uploads for this member",
    "askCarrier": "Member MCDANIEL, GENNETTE (eff 2026-01-01) is active on our books but does not appear on Brokerage Solutions (BSI) commission statements. Please pay the agency override of $150.00 per Humana Initial · National · THEI 50%.",
    "note": "On Hector; missing from Carrier→BSI",
    "state": "IN",
    "yearType": "Initial"
  },
  "CINDY|MCLEOD|humana": {
    "fightType": "Missing_pay",
    "fightTypePlain": "Not on BSI — carrier never paid override",
    "confidence": "HIGH",
    "sendOrder": 2,
    "carrier": "Humana",
    "client": "MCLEOD, CINDY",
    "agent": "TAYLOR, JILL A",
    "effectiveDate": "2026-01-01",
    "amount": 150,
    "theiShare": 75,
    "bsiShare": 75,
    "errorCode": "On Hector/active but NO pay on Carrier→BSI statements",
    "proof": "Hector=Active Policy; enrolled 2026-01-01; zero Agency Override on carrier→BSI uploads for this member",
    "askCarrier": "Member MCLEOD, CINDY (eff 2026-01-01) is active on our books but does not appear on Brokerage Solutions (BSI) commission statements. Please pay the agency override of $150.00 per Humana Initial · National · THEI 50%.",
    "note": "On Hector; missing from Carrier→BSI",
    "state": "FL",
    "yearType": "Initial"
  },
  "CLARENCE|JR|MEACHAM|humana": {
    "fightType": "Missing_pay",
    "fightTypePlain": "Not on BSI — carrier never paid override",
    "confidence": "HIGH",
    "sendOrder": 2,
    "carrier": "Humana",
    "client": "MEACHAM JR, CLARENCE R",
    "agent": "VANHEYNINGEN, JENDY",
    "effectiveDate": "2026-07-01",
    "amount": 150,
    "theiShare": 75,
    "bsiShare": 75,
    "errorCode": "On Hector/active but NO pay on Carrier→BSI statements",
    "proof": "Hector=Active Policy; enrolled 2026-07-01; zero Agency Override on carrier→BSI uploads for this member",
    "askCarrier": "Member MEACHAM JR, CLARENCE R (eff 2026-07-01) is active on our books but does not appear on Brokerage Solutions (BSI) commission statements. Please pay the agency override of $150.00 per Humana Initial · National · THEI 50%.",
    "note": "On Hector; missing from Carrier→BSI",
    "state": "UT",
    "yearType": "Initial"
  },
  "ETHA|MILES|humana": {
    "fightType": "Missing_pay",
    "fightTypePlain": "Not on BSI — carrier never paid override",
    "confidence": "HIGH",
    "sendOrder": 2,
    "carrier": "Humana",
    "client": "MILES, ETHA",
    "agent": "DEL VALLE, ERIC",
    "effectiveDate": "2026-01-01",
    "amount": 150,
    "theiShare": 75,
    "bsiShare": 75,
    "errorCode": "On Hector/active but NO pay on Carrier→BSI statements",
    "proof": "Hector=Active Policy; enrolled 2026-01-01; zero Agency Override on carrier→BSI uploads for this member",
    "askCarrier": "Member MILES, ETHA (eff 2026-01-01) is active on our books but does not appear on Brokerage Solutions (BSI) commission statements. Please pay the agency override of $150.00 per Humana Initial · National · THEI 50%.",
    "note": "On Hector; missing from Carrier→BSI",
    "state": "FL",
    "yearType": "Initial"
  },
  "MOORE|WILLIAM|humana": {
    "fightType": "Missing_pay",
    "fightTypePlain": "Not on BSI — carrier never paid override",
    "confidence": "HIGH",
    "sendOrder": 2,
    "carrier": "Humana",
    "client": "MOORE, WILLIAM",
    "agent": "VANHEYNINGEN, JENDY",
    "effectiveDate": "2026-01-01",
    "amount": 150,
    "theiShare": 75,
    "bsiShare": 75,
    "errorCode": "On Hector/active but NO pay on Carrier→BSI statements",
    "proof": "Hector=Active Policy; enrolled 2026-01-01; zero Agency Override on carrier→BSI uploads for this member",
    "askCarrier": "Member MOORE, WILLIAM (eff 2026-01-01) is active on our books but does not appear on Brokerage Solutions (BSI) commission statements. Please pay the agency override of $150.00 per Humana Initial · National · THEI 50%.",
    "note": "On Hector; missing from Carrier→BSI",
    "state": "MO",
    "yearType": "Initial"
  },
  "OSBORNE|SHARON|humana": {
    "fightType": "Missing_pay",
    "fightTypePlain": "Not on BSI — carrier never paid override",
    "confidence": "HIGH",
    "sendOrder": 2,
    "carrier": "Humana",
    "client": "OSBORNE, SHARON K",
    "agent": "VANHEYNINGEN, JENDY",
    "effectiveDate": "2026-01-01",
    "amount": 150,
    "theiShare": 75,
    "bsiShare": 75,
    "errorCode": "On Hector/active but NO pay on Carrier→BSI statements",
    "proof": "Hector=Active Policy; enrolled 2026-01-01; zero Agency Override on carrier→BSI uploads for this member",
    "askCarrier": "Member OSBORNE, SHARON K (eff 2026-01-01) is active on our books but does not appear on Brokerage Solutions (BSI) commission statements. Please pay the agency override of $150.00 per Humana Initial · National · THEI 50%.",
    "note": "On Hector; missing from Carrier→BSI",
    "state": "KY",
    "yearType": "Initial"
  },
  "FRANCISCO|PENA|humana": {
    "fightType": "Missing_pay",
    "fightTypePlain": "Not on BSI — carrier never paid override",
    "confidence": "HIGH",
    "sendOrder": 2,
    "carrier": "Humana",
    "client": "PENA, FRANCISCO",
    "agent": "VANHEYNINGEN, JENDY",
    "effectiveDate": "2026-08-01",
    "amount": 150,
    "theiShare": 75,
    "bsiShare": 75,
    "errorCode": "On Hector/active but NO pay on Carrier→BSI statements",
    "proof": "Hector=Active Policy; enrolled 2026-08-01; zero Agency Override on carrier→BSI uploads for this member",
    "askCarrier": "Member PENA, FRANCISCO (eff 2026-08-01) is active on our books but does not appear on Brokerage Solutions (BSI) commission statements. Please pay the agency override of $150.00 per Humana Initial · National · THEI 50%.",
    "note": "On Hector; missing from Carrier→BSI",
    "state": "TX",
    "yearType": "Initial"
  },
  "MARIA|PENA|humana": {
    "fightType": "Missing_pay",
    "fightTypePlain": "Not on BSI — carrier never paid override",
    "confidence": "HIGH",
    "sendOrder": 2,
    "carrier": "Humana",
    "client": "PENA, MARIA",
    "agent": "VANHEYNINGEN, JENDY",
    "effectiveDate": "2026-08-01",
    "amount": 150,
    "theiShare": 75,
    "bsiShare": 75,
    "errorCode": "On Hector/active but NO pay on Carrier→BSI statements",
    "proof": "Hector=Active Policy; enrolled 2026-08-01; zero Agency Override on carrier→BSI uploads for this member",
    "askCarrier": "Member PENA, MARIA (eff 2026-08-01) is active on our books but does not appear on Brokerage Solutions (BSI) commission statements. Please pay the agency override of $150.00 per Humana Initial · National · THEI 50%.",
    "note": "On Hector; missing from Carrier→BSI",
    "state": "TX",
    "yearType": "Initial"
  },
  "DEBORAH|PERRY|humana": {
    "fightType": "Missing_pay",
    "fightTypePlain": "Not on BSI — carrier never paid override",
    "confidence": "HIGH",
    "sendOrder": 2,
    "carrier": "Humana",
    "client": "PERRY, DEBORAH",
    "agent": "VANHEYNINGEN, JENDY",
    "effectiveDate": "2026-08-01",
    "amount": 150,
    "theiShare": 75,
    "bsiShare": 75,
    "errorCode": "On Hector/active but NO pay on Carrier→BSI statements",
    "proof": "Hector=Active Policy; enrolled 2026-08-01; zero Agency Override on carrier→BSI uploads for this member",
    "askCarrier": "Member PERRY, DEBORAH (eff 2026-08-01) is active on our books but does not appear on Brokerage Solutions (BSI) commission statements. Please pay the agency override of $150.00 per Humana Initial · National · THEI 50%.",
    "note": "On Hector; missing from Carrier→BSI",
    "state": "AL",
    "yearType": "Initial"
  },
  "DIANNE|PETERSON|humana": {
    "fightType": "Missing_pay",
    "fightTypePlain": "Not on BSI — carrier never paid override",
    "confidence": "HIGH",
    "sendOrder": 2,
    "carrier": "Humana",
    "client": "PETERSON, DIANNE",
    "agent": "SANTIAGO, IVAN",
    "effectiveDate": "2026-02-01",
    "amount": 150,
    "theiShare": 75,
    "bsiShare": 75,
    "errorCode": "On Hector/active but NO pay on Carrier→BSI statements",
    "proof": "Hector=Paid; enrolled 2026-02-01; zero Agency Override on carrier→BSI uploads for this member",
    "askCarrier": "Member PETERSON, DIANNE (eff 2026-02-01) is active on our books but does not appear on Brokerage Solutions (BSI) commission statements. Please pay the agency override of $150.00 per Humana Initial · National · THEI 50%.",
    "note": "On Hector; missing from Carrier→BSI",
    "state": "FL",
    "yearType": "Initial"
  },
  "DAVID|PHILLIPS|humana": {
    "fightType": "Missing_pay",
    "fightTypePlain": "Not on BSI — carrier never paid override",
    "confidence": "HIGH",
    "sendOrder": 2,
    "carrier": "Humana",
    "client": "PHILLIPS, DAVID",
    "agent": "ROSTRAN, PAULETTE",
    "effectiveDate": "2026-01-01",
    "amount": 150,
    "theiShare": 75,
    "bsiShare": 75,
    "errorCode": "On Hector/active but NO pay on Carrier→BSI statements",
    "proof": "Hector=Active Policy; enrolled 2026-01-01; zero Agency Override on carrier→BSI uploads for this member",
    "askCarrier": "Member PHILLIPS, DAVID (eff 2026-01-01) is active on our books but does not appear on Brokerage Solutions (BSI) commission statements. Please pay the agency override of $150.00 per Humana Initial · National · THEI 50%.",
    "note": "On Hector; missing from Carrier→BSI",
    "state": "FL",
    "yearType": "Initial"
  },
  "DANNY|RICHARDSON|humana": {
    "fightType": "Missing_pay",
    "fightTypePlain": "Not on BSI — carrier never paid override",
    "confidence": "HIGH",
    "sendOrder": 2,
    "carrier": "Humana",
    "client": "RICHARDSON, DANNY",
    "agent": "VANHEYNINGEN, JENDY",
    "effectiveDate": "2026-08-01",
    "amount": 150,
    "theiShare": 75,
    "bsiShare": 75,
    "errorCode": "On Hector/active but NO pay on Carrier→BSI statements",
    "proof": "Hector=Active Policy; enrolled 2026-08-01; zero Agency Override on carrier→BSI uploads for this member",
    "askCarrier": "Member RICHARDSON, DANNY (eff 2026-08-01) is active on our books but does not appear on Brokerage Solutions (BSI) commission statements. Please pay the agency override of $150.00 per Humana Initial · National · THEI 50%.",
    "note": "On Hector; missing from Carrier→BSI",
    "state": "NC",
    "yearType": "Initial"
  },
  "KATHERINE|RIVAS|humana": {
    "fightType": "Missing_pay",
    "fightTypePlain": "Not on BSI — carrier never paid override",
    "confidence": "HIGH",
    "sendOrder": 2,
    "carrier": "Humana",
    "client": "RIVAS, KATHERINE",
    "agent": "ELCHAMI, ALAN",
    "effectiveDate": "2026-01-01",
    "amount": 150,
    "theiShare": 75,
    "bsiShare": 75,
    "errorCode": "On Hector/active but NO pay on Carrier→BSI statements",
    "proof": "Hector=Active Policy; enrolled 2026-01-01; zero Agency Override on carrier→BSI uploads for this member",
    "askCarrier": "Member RIVAS, KATHERINE (eff 2026-01-01) is active on our books but does not appear on Brokerage Solutions (BSI) commission statements. Please pay the agency override of $150.00 per Humana Initial · National · THEI 50%.",
    "note": "On Hector; missing from Carrier→BSI",
    "state": "FL",
    "yearType": "Initial"
  },
  "ARIANI|RIVERO|humana": {
    "fightType": "Missing_pay",
    "fightTypePlain": "Not on BSI — carrier never paid override",
    "confidence": "HIGH",
    "sendOrder": 2,
    "carrier": "Humana",
    "client": "RIVERO, ARIANI",
    "agent": "ELCHAMI, ALAN",
    "effectiveDate": "2026-01-01",
    "amount": 150,
    "theiShare": 75,
    "bsiShare": 75,
    "errorCode": "On Hector/active but NO pay on Carrier→BSI statements",
    "proof": "Hector=Active Policy; enrolled 2026-01-01; zero Agency Override on carrier→BSI uploads for this member",
    "askCarrier": "Member RIVERO, ARIANI (eff 2026-01-01) is active on our books but does not appear on Brokerage Solutions (BSI) commission statements. Please pay the agency override of $150.00 per Humana Initial · National · THEI 50%.",
    "note": "On Hector; missing from Carrier→BSI",
    "state": "FL",
    "yearType": "Initial"
  },
  "BERNARDETE|RAMAN|RODRIGUES|humana": {
    "fightType": "Missing_pay",
    "fightTypePlain": "Not on BSI — carrier never paid override",
    "confidence": "HIGH",
    "sendOrder": 2,
    "carrier": "Humana",
    "client": "RODRIGUES RAMAN, BERNARDETE",
    "agent": "SANTIAGO, IVAN",
    "effectiveDate": "2026-01-01",
    "amount": 150,
    "theiShare": 75,
    "bsiShare": 75,
    "errorCode": "On Hector/active but NO pay on Carrier→BSI statements",
    "proof": "Hector=Active Policy; enrolled 2026-01-01; zero Agency Override on carrier→BSI uploads for this member",
    "askCarrier": "Member RODRIGUES RAMAN, BERNARDETE (eff 2026-01-01) is active on our books but does not appear on Brokerage Solutions (BSI) commission statements. Please pay the agency override of $150.00 per Humana Initial · National · THEI 50%.",
    "note": "On Hector; missing from Carrier→BSI",
    "state": "FL",
    "yearType": "Initial"
  },
  "MICHAEL|RODRIGUEZ|humana": {
    "fightType": "Missing_pay",
    "fightTypePlain": "Not on BSI — carrier never paid override",
    "confidence": "HIGH",
    "sendOrder": 2,
    "carrier": "Humana",
    "client": "RODRIGUEZ, MICHAEL",
    "agent": "VANHEYNINGEN, JENDY",
    "effectiveDate": "2026-03-01",
    "amount": 150,
    "theiShare": 75,
    "bsiShare": 75,
    "errorCode": "On Hector/active but NO pay on Carrier→BSI statements",
    "proof": "Hector=Paid; enrolled 2026-03-01; zero Agency Override on carrier→BSI uploads for this member",
    "askCarrier": "Member RODRIGUEZ, MICHAEL (eff 2026-03-01) is active on our books but does not appear on Brokerage Solutions (BSI) commission statements. Please pay the agency override of $150.00 per Humana Initial · National · THEI 50%.",
    "note": "On Hector; missing from Carrier→BSI",
    "state": "FL",
    "yearType": "Initial"
  },
  "BAHRAM|ROOSTA|humana": {
    "fightType": "Missing_pay",
    "fightTypePlain": "Not on BSI — carrier never paid override",
    "confidence": "HIGH",
    "sendOrder": 2,
    "carrier": "Humana",
    "client": "ROOSTA, BAHRAM",
    "agent": "ELCHAMI, ALAN",
    "effectiveDate": "2026-01-01",
    "amount": 150,
    "theiShare": 75,
    "bsiShare": 75,
    "errorCode": "On Hector/active but NO pay on Carrier→BSI statements",
    "proof": "Hector=Active Policy; enrolled 2026-01-01; zero Agency Override on carrier→BSI uploads for this member",
    "askCarrier": "Member ROOSTA, BAHRAM (eff 2026-01-01) is active on our books but does not appear on Brokerage Solutions (BSI) commission statements. Please pay the agency override of $150.00 per Humana Initial · National · THEI 50%.",
    "note": "On Hector; missing from Carrier→BSI",
    "state": "FL",
    "yearType": "Initial"
  },
  "ANA|SANCHEZ|humana": {
    "fightType": "Missing_pay",
    "fightTypePlain": "Not on BSI — carrier never paid override",
    "confidence": "HIGH",
    "sendOrder": 2,
    "carrier": "Humana",
    "client": "SANCHEZ, ANA",
    "agent": "NICHELSON, JEREMY J",
    "effectiveDate": "2026-01-01",
    "amount": 150,
    "theiShare": 75,
    "bsiShare": 75,
    "errorCode": "On Hector/active but NO pay on Carrier→BSI statements",
    "proof": "Hector=Active Policy; enrolled 2026-01-01; zero Agency Override on carrier→BSI uploads for this member",
    "askCarrier": "Member SANCHEZ, ANA (eff 2026-01-01) is active on our books but does not appear on Brokerage Solutions (BSI) commission statements. Please pay the agency override of $150.00 per Humana Initial · National · THEI 50%.",
    "note": "On Hector; missing from Carrier→BSI",
    "state": "FL",
    "yearType": "Initial"
  },
  "PATRICIA|SARGENT|humana": {
    "fightType": "Missing_pay",
    "fightTypePlain": "Not on BSI — carrier never paid override",
    "confidence": "HIGH",
    "sendOrder": 2,
    "carrier": "Humana",
    "client": "SARGENT, PATRICIA",
    "agent": "VANHEYNINGEN, JENDY",
    "effectiveDate": "2026-01-01",
    "amount": 150,
    "theiShare": 75,
    "bsiShare": 75,
    "errorCode": "On Hector/active but NO pay on Carrier→BSI statements",
    "proof": "Hector=Active Policy; enrolled 2026-01-01; zero Agency Override on carrier→BSI uploads for this member",
    "askCarrier": "Member SARGENT, PATRICIA (eff 2026-01-01) is active on our books but does not appear on Brokerage Solutions (BSI) commission statements. Please pay the agency override of $150.00 per Humana Initial · National · THEI 50%.",
    "note": "On Hector; missing from Carrier→BSI",
    "state": "CO",
    "yearType": "Initial"
  },
  "SCARBERRY|THOMAS|humana": {
    "fightType": "Missing_pay",
    "fightTypePlain": "Not on BSI — carrier never paid override",
    "confidence": "HIGH",
    "sendOrder": 2,
    "carrier": "Humana",
    "client": "SCARBERRY, THOMAS",
    "agent": "ELCHAMI, ALAN",
    "effectiveDate": "2026-01-01",
    "amount": 150,
    "theiShare": 75,
    "bsiShare": 75,
    "errorCode": "On Hector/active but NO pay on Carrier→BSI statements",
    "proof": "Hector=Active Policy; enrolled 2026-01-01; zero Agency Override on carrier→BSI uploads for this member",
    "askCarrier": "Member SCARBERRY, THOMAS (eff 2026-01-01) is active on our books but does not appear on Brokerage Solutions (BSI) commission statements. Please pay the agency override of $150.00 per Humana Initial · National · THEI 50%.",
    "note": "On Hector; missing from Carrier→BSI",
    "state": "FL",
    "yearType": "Initial"
  },
  "SHAWN|SOKOLOSKIS|humana": {
    "fightType": "Missing_pay",
    "fightTypePlain": "Not on BSI — carrier never paid override",
    "confidence": "HIGH",
    "sendOrder": 2,
    "carrier": "Humana",
    "client": "SOKOLOSKIS, SHAWN",
    "agent": "ELCHAMI, ALAN",
    "effectiveDate": "2026-01-01",
    "amount": 150,
    "theiShare": 75,
    "bsiShare": 75,
    "errorCode": "On Hector/active but NO pay on Carrier→BSI statements",
    "proof": "Hector=Active Policy; enrolled 2026-01-01; zero Agency Override on carrier→BSI uploads for this member",
    "askCarrier": "Member SOKOLOSKIS, SHAWN (eff 2026-01-01) is active on our books but does not appear on Brokerage Solutions (BSI) commission statements. Please pay the agency override of $150.00 per Humana Initial · National · THEI 50%.",
    "note": "On Hector; missing from Carrier→BSI",
    "state": "FL",
    "yearType": "Initial"
  },
  "BORRERO|NILDA|SOSA|humana": {
    "fightType": "Missing_pay",
    "fightTypePlain": "Not on BSI — carrier never paid override",
    "confidence": "HIGH",
    "sendOrder": 2,
    "carrier": "Humana",
    "client": "SOSA-BORRERO, NILDA",
    "agent": "PEREZ, YAHOSKA G",
    "effectiveDate": "2026-01-01",
    "amount": 150,
    "theiShare": 75,
    "bsiShare": 75,
    "errorCode": "On Hector/active but NO pay on Carrier→BSI statements",
    "proof": "Hector=Active Policy; enrolled 2026-01-01; zero Agency Override on carrier→BSI uploads for this member",
    "askCarrier": "Member SOSA-BORRERO, NILDA (eff 2026-01-01) is active on our books but does not appear on Brokerage Solutions (BSI) commission statements. Please pay the agency override of $150.00 per Humana Initial · National · THEI 50%.",
    "note": "On Hector; missing from Carrier→BSI",
    "state": "FL",
    "yearType": "Initial"
  },
  "JEAN|SUBTIL|humana": {
    "fightType": "Missing_pay",
    "fightTypePlain": "Not on BSI — carrier never paid override",
    "confidence": "HIGH",
    "sendOrder": 2,
    "carrier": "Humana",
    "client": "SUBTIL, JEAN",
    "agent": "ELCHAMI, ALAN",
    "effectiveDate": "2026-01-01",
    "amount": 150,
    "theiShare": 75,
    "bsiShare": 75,
    "errorCode": "On Hector/active but NO pay on Carrier→BSI statements",
    "proof": "Hector=Active Policy; enrolled 2026-01-01; zero Agency Override on carrier→BSI uploads for this member",
    "askCarrier": "Member SUBTIL, JEAN (eff 2026-01-01) is active on our books but does not appear on Brokerage Solutions (BSI) commission statements. Please pay the agency override of $150.00 per Humana Initial · National · THEI 50%.",
    "note": "On Hector; missing from Carrier→BSI",
    "state": "FL",
    "yearType": "Initial"
  },
  "PEDRO|POL|TABARES|humana": {
    "fightType": "Missing_pay",
    "fightTypePlain": "Not on BSI — carrier never paid override",
    "confidence": "HIGH",
    "sendOrder": 2,
    "carrier": "Humana",
    "client": "TABARES POL, PEDRO",
    "agent": "ELCHAMI, ALAN",
    "effectiveDate": "2026-01-01",
    "amount": 150,
    "theiShare": 75,
    "bsiShare": 75,
    "errorCode": "On Hector/active but NO pay on Carrier→BSI statements",
    "proof": "Hector=Active Policy; enrolled 2026-01-01; zero Agency Override on carrier→BSI uploads for this member",
    "askCarrier": "Member TABARES POL, PEDRO (eff 2026-01-01) is active on our books but does not appear on Brokerage Solutions (BSI) commission statements. Please pay the agency override of $150.00 per Humana Initial · National · THEI 50%.",
    "note": "On Hector; missing from Carrier→BSI",
    "state": "FL",
    "yearType": "Initial"
  },
  "GEORGE|THOMAS|humana": {
    "fightType": "Missing_pay",
    "fightTypePlain": "Not on BSI — carrier never paid override",
    "confidence": "HIGH",
    "sendOrder": 2,
    "carrier": "Humana",
    "client": "THOMAS, GEORGE",
    "agent": "VANHEYNINGEN, JENDY",
    "effectiveDate": "2026-08-01",
    "amount": 150,
    "theiShare": 75,
    "bsiShare": 75,
    "errorCode": "On Hector/active but NO pay on Carrier→BSI statements",
    "proof": "Hector=Active Policy; enrolled 2026-08-01; zero Agency Override on carrier→BSI uploads for this member",
    "askCarrier": "Member THOMAS, GEORGE (eff 2026-08-01) is active on our books but does not appear on Brokerage Solutions (BSI) commission statements. Please pay the agency override of $150.00 per Humana Initial · National · THEI 50%.",
    "note": "On Hector; missing from Carrier→BSI",
    "state": "LA",
    "yearType": "Initial"
  },
  "ANITA|TOLER|humana": {
    "fightType": "Missing_pay",
    "fightTypePlain": "Not on BSI — carrier never paid override",
    "confidence": "HIGH",
    "sendOrder": 2,
    "carrier": "Humana",
    "client": "TOLER, ANITA",
    "agent": "VANHEYNINGEN, JENDY",
    "effectiveDate": "2026-08-01",
    "amount": 150,
    "theiShare": 75,
    "bsiShare": 75,
    "errorCode": "On Hector/active but NO pay on Carrier→BSI statements",
    "proof": "Hector=Active Policy; enrolled 2026-08-01; zero Agency Override on carrier→BSI uploads for this member",
    "askCarrier": "Member TOLER, ANITA (eff 2026-08-01) is active on our books but does not appear on Brokerage Solutions (BSI) commission statements. Please pay the agency override of $150.00 per Humana Initial · National · THEI 50%.",
    "note": "On Hector; missing from Carrier→BSI",
    "state": "NC",
    "yearType": "Initial"
  },
  "HORACE|WALTERS|humana": {
    "fightType": "Missing_pay",
    "fightTypePlain": "Not on BSI — carrier never paid override",
    "confidence": "HIGH",
    "sendOrder": 2,
    "carrier": "Humana",
    "client": "WALTERS, HORACE",
    "agent": "ELCHAMI, ALAN",
    "effectiveDate": "2026-01-01",
    "amount": 150,
    "theiShare": 75,
    "bsiShare": 75,
    "errorCode": "On Hector/active but NO pay on Carrier→BSI statements",
    "proof": "Hector=Active Policy; enrolled 2026-01-01; zero Agency Override on carrier→BSI uploads for this member",
    "askCarrier": "Member WALTERS, HORACE (eff 2026-01-01) is active on our books but does not appear on Brokerage Solutions (BSI) commission statements. Please pay the agency override of $150.00 per Humana Initial · National · THEI 50%.",
    "note": "On Hector; missing from Carrier→BSI",
    "state": "FL",
    "yearType": "Initial"
  },
  "RONNIE|WILLIAMS|humana": {
    "fightType": "Missing_pay",
    "fightTypePlain": "Not on BSI — carrier never paid override",
    "confidence": "HIGH",
    "sendOrder": 2,
    "carrier": "Humana",
    "client": "WILLIAMS, RONNIE",
    "agent": "CARPENTER, KELLY E",
    "effectiveDate": "2026-08-01",
    "amount": 150,
    "theiShare": 75,
    "bsiShare": 75,
    "errorCode": "On Hector/active but NO pay on Carrier→BSI statements",
    "proof": "Hector=Active Policy; enrolled 2026-08-01; zero Agency Override on carrier→BSI uploads for this member",
    "askCarrier": "Member WILLIAMS, RONNIE (eff 2026-08-01) is active on our books but does not appear on Brokerage Solutions (BSI) commission statements. Please pay the agency override of $150.00 per Humana Initial · National · THEI 50%.",
    "note": "On Hector; missing from Carrier→BSI",
    "state": "GA",
    "yearType": "Initial"
  },
  "JEFFERY|WILSON|humana": {
    "fightType": "Missing_pay",
    "fightTypePlain": "Not on BSI — carrier never paid override",
    "confidence": "HIGH",
    "sendOrder": 2,
    "carrier": "Humana",
    "client": "WILSON, JEFFERY",
    "agent": "VANHEYNINGEN, JENDY",
    "effectiveDate": "2026-01-01",
    "amount": 150,
    "theiShare": 75,
    "bsiShare": 75,
    "errorCode": "On Hector/active but NO pay on Carrier→BSI statements",
    "proof": "Hector=Active Policy; enrolled 2026-01-01; zero Agency Override on carrier→BSI uploads for this member",
    "askCarrier": "Member WILSON, JEFFERY (eff 2026-01-01) is active on our books but does not appear on Brokerage Solutions (BSI) commission statements. Please pay the agency override of $150.00 per Humana Initial · National · THEI 50%.",
    "note": "On Hector; missing from Carrier→BSI",
    "state": "KY",
    "yearType": "Initial"
  },
  "LESLIE|MICHAEL|unitedhealthcare": {
    "fightType": "Missing_pay",
    "fightTypePlain": "Not on BSI — carrier never paid override",
    "confidence": "HIGH",
    "sendOrder": 2,
    "carrier": "UnitedHealthcare",
    "client": "MICHAEL LESLIE",
    "agent": "RIVERA, MICHAEL",
    "effectiveDate": "2026-01-01",
    "amount": 175,
    "theiShare": 87.5,
    "bsiShare": 87.5,
    "errorCode": "On Hector/active but NO pay on Carrier→BSI statements",
    "proof": "Hector=COMPLETED; enrolled 2026-01-01; zero Agency Override on carrier→BSI uploads for this member",
    "askCarrier": "Member MICHAEL LESLIE (eff 2026-01-01) is active on our books but does not appear on Brokerage Solutions (BSI) commission statements. Please pay the agency override of $175.00 per UHC Initial · California · THEI 50%.",
    "note": "On Hector; missing from Carrier→BSI",
    "state": "CA",
    "yearType": "Initial"
  },
  "ANNETTE|POMPEY|unitedhealthcare": {
    "fightType": "Missing_pay",
    "fightTypePlain": "Not on BSI — carrier never paid override",
    "confidence": "HIGH",
    "sendOrder": 2,
    "carrier": "UnitedHealthcare",
    "client": "ANNETTE POMPEY",
    "agent": "KHUU, LONG",
    "effectiveDate": "2026-01-01",
    "amount": 150,
    "theiShare": 75,
    "bsiShare": 75,
    "errorCode": "On Hector/active but NO pay on Carrier→BSI statements",
    "proof": "Hector=COMPLETED; enrolled 2026-01-01; zero Agency Override on carrier→BSI uploads for this member",
    "askCarrier": "Member ANNETTE POMPEY (eff 2026-01-01) is active on our books but does not appear on Brokerage Solutions (BSI) commission statements. Please pay the agency override of $150.00 per UHC Initial · National · THEI 50%.",
    "note": "On Hector; missing from Carrier→BSI",
    "state": "FL",
    "yearType": "Initial"
  },
  "ANNETTE|SANDERS|unitedhealthcare": {
    "fightType": "Missing_pay",
    "fightTypePlain": "Not on BSI — carrier never paid override",
    "confidence": "HIGH",
    "sendOrder": 2,
    "carrier": "UnitedHealthcare",
    "client": "ANNETTE SANDERS",
    "agent": "MCCALLA, NICHOLAS",
    "effectiveDate": "2026-01-01",
    "amount": 150,
    "theiShare": 75,
    "bsiShare": 75,
    "errorCode": "On Hector/active but NO pay on Carrier→BSI statements",
    "proof": "Hector=COMPLETED; enrolled 2026-01-01; zero Agency Override on carrier→BSI uploads for this member",
    "askCarrier": "Member ANNETTE SANDERS (eff 2026-01-01) is active on our books but does not appear on Brokerage Solutions (BSI) commission statements. Please pay the agency override of $150.00 per UHC Initial · National · THEI 50%.",
    "note": "On Hector; missing from Carrier→BSI",
    "state": "TX",
    "yearType": "Initial"
  },
  "ARLENDIA|HINES|unitedhealthcare": {
    "fightType": "Missing_pay",
    "fightTypePlain": "Not on BSI — carrier never paid override",
    "confidence": "HIGH",
    "sendOrder": 2,
    "carrier": "UnitedHealthcare",
    "client": "ARLENDIA HINES",
    "agent": "VANHEYNINGEN, JENDY",
    "effectiveDate": "2026-08-01",
    "amount": 150,
    "theiShare": 75,
    "bsiShare": 75,
    "errorCode": "On Hector/active but NO pay on Carrier→BSI statements",
    "proof": "Hector=COMPLETED; enrolled 2026-08-01; zero Agency Override on carrier→BSI uploads for this member",
    "askCarrier": "Member ARLENDIA HINES (eff 2026-08-01) is active on our books but does not appear on Brokerage Solutions (BSI) commission statements. Please pay the agency override of $150.00 per UHC Initial · National · THEI 50%.",
    "note": "On Hector; missing from Carrier→BSI",
    "state": "NC",
    "yearType": "Initial"
  },
  "BERNICE|HAYES|unitedhealthcare": {
    "fightType": "Missing_pay",
    "fightTypePlain": "Not on BSI — carrier never paid override",
    "confidence": "HIGH",
    "sendOrder": 2,
    "carrier": "UnitedHealthcare",
    "client": "BERNICE HAYES",
    "agent": "CLAWSON, FRANK",
    "effectiveDate": "2026-01-01",
    "amount": 150,
    "theiShare": 75,
    "bsiShare": 75,
    "errorCode": "On Hector/active but NO pay on Carrier→BSI statements",
    "proof": "Hector=COMPLETED; enrolled 2026-01-01; zero Agency Override on carrier→BSI uploads for this member",
    "askCarrier": "Member BERNICE HAYES (eff 2026-01-01) is active on our books but does not appear on Brokerage Solutions (BSI) commission statements. Please pay the agency override of $150.00 per UHC Initial · National · THEI 50%.",
    "note": "On Hector; missing from Carrier→BSI",
    "state": "TN",
    "yearType": "Initial"
  },
  "BETTY|GOODLOE|unitedhealthcare": {
    "fightType": "Missing_pay",
    "fightTypePlain": "Not on BSI — carrier never paid override",
    "confidence": "HIGH",
    "sendOrder": 2,
    "carrier": "UnitedHealthcare",
    "client": "BETTY GOODLOE",
    "agent": "VANHEYNINGEN, JENDY",
    "effectiveDate": "2026-08-01",
    "amount": 150,
    "theiShare": 75,
    "bsiShare": 75,
    "errorCode": "On Hector/active but NO pay on Carrier→BSI statements",
    "proof": "Hector=COMPLETED; enrolled 2026-08-01; zero Agency Override on carrier→BSI uploads for this member",
    "askCarrier": "Member BETTY GOODLOE (eff 2026-08-01) is active on our books but does not appear on Brokerage Solutions (BSI) commission statements. Please pay the agency override of $150.00 per UHC Initial · National · THEI 50%.",
    "note": "On Hector; missing from Carrier→BSI",
    "state": "AL",
    "yearType": "Initial"
  },
  "JANIE|NORFLEET|unitedhealthcare": {
    "fightType": "Missing_pay",
    "fightTypePlain": "Not on BSI — carrier never paid override",
    "confidence": "HIGH",
    "sendOrder": 2,
    "carrier": "UnitedHealthcare",
    "client": "JANIE NORFLEET",
    "agent": "RIVERA, MICHAEL",
    "effectiveDate": "2026-01-01",
    "amount": 150,
    "theiShare": 75,
    "bsiShare": 75,
    "errorCode": "On Hector/active but NO pay on Carrier→BSI statements",
    "proof": "Hector=COMPLETED; enrolled 2026-01-01; zero Agency Override on carrier→BSI uploads for this member",
    "askCarrier": "Member JANIE NORFLEET (eff 2026-01-01) is active on our books but does not appear on Brokerage Solutions (BSI) commission statements. Please pay the agency override of $150.00 per UHC Initial · National · THEI 50%.",
    "note": "On Hector; missing from Carrier→BSI",
    "state": "KY",
    "yearType": "Initial"
  },
  "BROWN|JUDY|unitedhealthcare": {
    "fightType": "Missing_pay",
    "fightTypePlain": "Not on BSI — carrier never paid override",
    "confidence": "HIGH",
    "sendOrder": 2,
    "carrier": "UnitedHealthcare",
    "client": "JUDY BROWN",
    "agent": "CRUZ, ADRIAN",
    "effectiveDate": "2026-01-01",
    "amount": 150,
    "theiShare": 75,
    "bsiShare": 75,
    "errorCode": "On Hector/active but NO pay on Carrier→BSI statements",
    "proof": "Hector=COMPLETED; enrolled 2026-01-01; zero Agency Override on carrier→BSI uploads for this member",
    "askCarrier": "Member JUDY BROWN (eff 2026-01-01) is active on our books but does not appear on Brokerage Solutions (BSI) commission statements. Please pay the agency override of $150.00 per UHC Initial · National · THEI 50%.",
    "note": "On Hector; missing from Carrier→BSI",
    "state": "IL",
    "yearType": "Initial"
  },
  "KAM|LING|WU|unitedhealthcare": {
    "fightType": "Missing_pay",
    "fightTypePlain": "Not on BSI — carrier never paid override",
    "confidence": "HIGH",
    "sendOrder": 2,
    "carrier": "UnitedHealthcare",
    "client": "KAM LING WU",
    "agent": "THE HEALTH EXPERTS INSURANCE",
    "effectiveDate": "2026-01-01",
    "amount": 150,
    "theiShare": 75,
    "bsiShare": 75,
    "errorCode": "On Hector/active but NO pay on Carrier→BSI statements",
    "proof": "Hector=Paid; enrolled 2026-01-01; zero Agency Override on carrier→BSI uploads for this member",
    "askCarrier": "Member KAM LING WU (eff 2026-01-01) is active on our books but does not appear on Brokerage Solutions (BSI) commission statements. Please pay the agency override of $150.00 per UHC Initial · National · THEI 50%.",
    "note": "On Hector; missing from Carrier→BSI",
    "state": "FL",
    "yearType": "Initial"
  },
  "LORINE|TUCKER|unitedhealthcare": {
    "fightType": "Missing_pay",
    "fightTypePlain": "Not on BSI — carrier never paid override",
    "confidence": "HIGH",
    "sendOrder": 2,
    "carrier": "UnitedHealthcare",
    "client": "LORINE TUCKER",
    "agent": "VANHEYNINGEN, JENDY",
    "effectiveDate": "2026-08-01",
    "amount": 150,
    "theiShare": 75,
    "bsiShare": 75,
    "errorCode": "On Hector/active but NO pay on Carrier→BSI statements",
    "proof": "Hector=COMPLETED; enrolled 2026-08-01; zero Agency Override on carrier→BSI uploads for this member",
    "askCarrier": "Member LORINE TUCKER (eff 2026-08-01) is active on our books but does not appear on Brokerage Solutions (BSI) commission statements. Please pay the agency override of $150.00 per UHC Initial · National · THEI 50%.",
    "note": "On Hector; missing from Carrier→BSI",
    "state": "AL",
    "yearType": "Initial"
  },
  "CALLE|MARTHA|unitedhealthcare": {
    "fightType": "Missing_pay",
    "fightTypePlain": "Not on BSI — carrier never paid override",
    "confidence": "HIGH",
    "sendOrder": 2,
    "carrier": "UnitedHealthcare",
    "client": "MARTHA CALLE",
    "agent": "THE HEALTH EXPERTS INSURANCE",
    "effectiveDate": "2026-01-01",
    "amount": 150,
    "theiShare": 75,
    "bsiShare": 75,
    "errorCode": "On Hector/active but NO pay on Carrier→BSI statements",
    "proof": "Hector=COMPLETED; enrolled 2026-01-01; zero Agency Override on carrier→BSI uploads for this member",
    "askCarrier": "Member MARTHA CALLE (eff 2026-01-01) is active on our books but does not appear on Brokerage Solutions (BSI) commission statements. Please pay the agency override of $150.00 per UHC Initial · National · THEI 50%.",
    "note": "On Hector; missing from Carrier→BSI",
    "state": "FL",
    "yearType": "Initial"
  },
  "CARMAN|MARY|unitedhealthcare": {
    "fightType": "Missing_pay",
    "fightTypePlain": "Not on BSI — carrier never paid override",
    "confidence": "HIGH",
    "sendOrder": 2,
    "carrier": "UnitedHealthcare",
    "client": "MARY CARMAN",
    "agent": "THE HEALTH EXPERTS INSURANCE",
    "effectiveDate": "2025-12-01",
    "amount": 150,
    "theiShare": 75,
    "bsiShare": 75,
    "errorCode": "On Hector/active but NO pay on Carrier→BSI statements",
    "proof": "Hector=COMPLETED; enrolled 2025-12-01; zero Agency Override on carrier→BSI uploads for this member",
    "askCarrier": "Member MARY CARMAN (eff 2025-12-01) is active on our books but does not appear on Brokerage Solutions (BSI) commission statements. Please pay the agency override of $150.00 per UHC Initial · National · THEI 50%.",
    "note": "On Hector; missing from Carrier→BSI",
    "state": "FL",
    "yearType": "Initial"
  },
  "PATRICIO|ROMERO|WILLS|unitedhealthcare": {
    "fightType": "Missing_pay",
    "fightTypePlain": "Not on BSI — carrier never paid override",
    "confidence": "HIGH",
    "sendOrder": 2,
    "carrier": "UnitedHealthcare",
    "client": "PATRICIO WILLS ROMERO",
    "agent": "THE HEALTH EXPERTS INSURANCE",
    "effectiveDate": "2026-03-01",
    "amount": 150,
    "theiShare": 75,
    "bsiShare": 75,
    "errorCode": "On Hector/active but NO pay on Carrier→BSI statements",
    "proof": "Hector=Paid; enrolled 2026-03-01; zero Agency Override on carrier→BSI uploads for this member",
    "askCarrier": "Member PATRICIO WILLS ROMERO (eff 2026-03-01) is active on our books but does not appear on Brokerage Solutions (BSI) commission statements. Please pay the agency override of $150.00 per UHC Initial · National · THEI 50%.",
    "note": "On Hector; missing from Carrier→BSI",
    "state": "FL",
    "yearType": "Initial"
  },
  "PHILOMENA|VITALE|unitedhealthcare": {
    "fightType": "Missing_pay",
    "fightTypePlain": "Not on BSI — carrier never paid override",
    "confidence": "HIGH",
    "sendOrder": 2,
    "carrier": "UnitedHealthcare",
    "client": "PHILOMENA VITALE",
    "agent": "CLAWSON, FRANK",
    "effectiveDate": "2026-01-01",
    "amount": 150,
    "theiShare": 75,
    "bsiShare": 75,
    "errorCode": "On Hector/active but NO pay on Carrier→BSI statements",
    "proof": "Hector=COMPLETED; enrolled 2026-01-01; zero Agency Override on carrier→BSI uploads for this member",
    "askCarrier": "Member PHILOMENA VITALE (eff 2026-01-01) is active on our books but does not appear on Brokerage Solutions (BSI) commission statements. Please pay the agency override of $150.00 per UHC Initial · National · THEI 50%.",
    "note": "On Hector; missing from Carrier→BSI",
    "state": "FL",
    "yearType": "Initial"
  },
  "KIPP|ROBERT|unitedhealthcare": {
    "fightType": "Missing_pay",
    "fightTypePlain": "Not on BSI — carrier never paid override",
    "confidence": "HIGH",
    "sendOrder": 2,
    "carrier": "UnitedHealthcare",
    "client": "ROBERT KIPP",
    "agent": "MCCALLA, NICHOLAS",
    "effectiveDate": "2026-01-01",
    "amount": 150,
    "theiShare": 75,
    "bsiShare": 75,
    "errorCode": "On Hector/active but NO pay on Carrier→BSI statements",
    "proof": "Hector=COMPLETED; enrolled 2026-01-01; zero Agency Override on carrier→BSI uploads for this member",
    "askCarrier": "Member ROBERT KIPP (eff 2026-01-01) is active on our books but does not appear on Brokerage Solutions (BSI) commission statements. Please pay the agency override of $150.00 per UHC Initial · National · THEI 50%.",
    "note": "On Hector; missing from Carrier→BSI",
    "state": "FL",
    "yearType": "Initial"
  },
  "SALLY|WILLIAMSON|unitedhealthcare": {
    "fightType": "Missing_pay",
    "fightTypePlain": "Not on BSI — carrier never paid override",
    "confidence": "HIGH",
    "sendOrder": 2,
    "carrier": "UnitedHealthcare",
    "client": "SALLY WILLIAMSON",
    "agent": "VANHEYNINGEN, JENDY",
    "effectiveDate": "2026-03-01",
    "amount": 150,
    "theiShare": 75,
    "bsiShare": 75,
    "errorCode": "On Hector/active but NO pay on Carrier→BSI statements",
    "proof": "Hector=Paid; enrolled 2026-03-01; zero Agency Override on carrier→BSI uploads for this member",
    "askCarrier": "Member SALLY WILLIAMSON (eff 2026-03-01) is active on our books but does not appear on Brokerage Solutions (BSI) commission statements. Please pay the agency override of $150.00 per UHC Initial · National · THEI 50%.",
    "note": "On Hector; missing from Carrier→BSI",
    "state": "OR",
    "yearType": "Initial"
  },
  "ALLEN|SHAHEERAH|unitedhealthcare": {
    "fightType": "Missing_pay",
    "fightTypePlain": "Not on BSI — carrier never paid override",
    "confidence": "HIGH",
    "sendOrder": 2,
    "carrier": "UnitedHealthcare",
    "client": "SHAHEERAH ALLEN",
    "agent": "MCCALLA, NICHOLAS",
    "effectiveDate": "2026-01-01",
    "amount": 150,
    "theiShare": 75,
    "bsiShare": 75,
    "errorCode": "On Hector/active but NO pay on Carrier→BSI statements",
    "proof": "Hector=COMPLETED; enrolled 2026-01-01; zero Agency Override on carrier→BSI uploads for this member",
    "askCarrier": "Member SHAHEERAH ALLEN (eff 2026-01-01) is active on our books but does not appear on Brokerage Solutions (BSI) commission statements. Please pay the agency override of $150.00 per UHC Initial · New Jersey · THEI 50%.",
    "note": "On Hector; missing from Carrier→BSI",
    "state": "NJ",
    "yearType": "Initial"
  },
  "CHAMBERS|VERONICA|unitedhealthcare": {
    "fightType": "Missing_pay",
    "fightTypePlain": "Not on BSI — carrier never paid override",
    "confidence": "HIGH",
    "sendOrder": 2,
    "carrier": "UnitedHealthcare",
    "client": "VERONICA CHAMBERS",
    "agent": "RIVERA, MICHAEL",
    "effectiveDate": "2026-01-01",
    "amount": 150,
    "theiShare": 75,
    "bsiShare": 75,
    "errorCode": "On Hector/active but NO pay on Carrier→BSI statements",
    "proof": "Hector=COMPLETED; enrolled 2026-01-01; zero Agency Override on carrier→BSI uploads for this member",
    "askCarrier": "Member VERONICA CHAMBERS (eff 2026-01-01) is active on our books but does not appear on Brokerage Solutions (BSI) commission statements. Please pay the agency override of $150.00 per UHC Initial · National · THEI 50%.",
    "note": "On Hector; missing from Carrier→BSI",
    "state": "NC",
    "yearType": "Initial"
  }
};

export default CARRIER_FIGHT_PACK_INDEX;
